import React,{useState} from 'react';
import {Link} from 'react-router-dom';
import {checklistItems,guideArticles} from './guideArticles';
import './GuideArticle.css';

const GuideArticle=({match,location})=>{const article=guideArticles.find((item)=>item.slug===match.params.slug);const isWorkGuide=location.pathname.startsWith('/joburi/ghid/');const backPath=isWorkGuide?'/joburi':'/viata-in-norvegia';const backLabel=isWorkGuide?'Muncă și acte':'Viața în Norvegia';const guideBase=isWorkGuide?'/joburi/ghid':'/viata-in-norvegia/ghid';const[checked,setChecked]=useState(()=>{try{return JSON.parse(localStorage.getItem('norway_first30_checklist'))||{}}catch(_){return{}}});if(!article)return <div className="guide-missing"><h1>Articolul nu a fost găsit</h1><Link to={backPath}>Înapoi la articole</Link></div>;const toggle=(item)=>{const next={...checked,[item]:!checked[item]};setChecked(next);localStorage.setItem('norway_first30_checklist',JSON.stringify(next))};const currentIndex=guideArticles.findIndex((item)=>item.slug===article.slug);const nextArticle=guideArticles[currentIndex+1];return <article className="reader">
 <Link className="reader__back" to={backPath}>← {backLabel}</Link><header className="reader__header"><p>{article.category}</p><h1>{article.title}</h1><div><span>{article.readTime} minute de citit</span><span>Actualizat în iulie 2026</span></div><strong>{article.excerpt}</strong></header>
 <div className="reader__layout"><aside><span>În acest articol</span>{article.sections.map((section,index)=><a href={`#section-${index}`} key={section.title}>{section.title}</a>)}</aside><main><p className="reader__intro">{article.intro}</p>{article.sections.map((section,index)=><section id={`section-${index}`} key={section.title}><span className="reader__section-number">{String(index+1).padStart(2,'0')}</span><h2>{section.title}</h2>{section.paragraphs.map((paragraph)=><p key={paragraph}>{paragraph}</p>)}{section.tips&&<div className="reader__tips"><strong>De reținut</strong>{section.tips.map((tip)=><p key={tip}>✓ {tip}</p>)}</div>}</section>)}
 {article.checklist&&<section className="reader-checklist"><div><span>Checklist personal</span><h2>Marchează pașii rezolvați</h2><p>Progresul este salvat numai în acest browser.</p></div>{checklistItems.map((item)=><label className={checked[item]?'done':''} key={item}><input type="checkbox" checked={Boolean(checked[item])} onChange={()=>toggle(item)}/><span>✓</span><p>{item}</p></label>)}</section>}
 {article.sources.length>0&&<section className="reader__sources"><h2>Surse oficiale</h2><p>Procedurile se pot modifica. Verifică situația ta direct la instituția competentă.</p>{article.sources.map(([label,url])=><a href={url} target="_blank" rel="noopener noreferrer" key={url}>{label} ↗</a>)}</section>}
 <div className="reader__language"><div><span>Continuă în aplicație</span><h2>Învață limba pentru situații reale</h2><p>Cursul A1 include dialoguri pentru muncă, cumpărături și viața de zi cu zi.</p></div><Link to="/invata">Deschide cursul →</Link></div>
 </main></div>{nextArticle&&<footer className="reader__next"><span>Articolul următor</span><h2>{nextArticle.title}</h2><Link to={`${guideBase}/${nextArticle.slug}`}>Continuă lectura →</Link></footer>}
 </article>};
export default GuideArticle;
