import React, { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { courseLessons } from '../lessons/norwegian-program/lessonContent';
import { speakNorwegian } from '../../services/norwegianSpeech';
import { saveReviewItem } from '../../services/spacedReview';
import './PracticeGame.css';

const shuffle=(items)=>[...items].sort(()=>Math.random()-.5);
const gameInfo={quiz:{title:'Chestionar',subtitle:'Verifică vocabularul și expresiile din lecții.',icon:'✅'},order:{title:'Construiește propoziția',subtitle:'Așază cuvintele în ordinea corectă.',icon:'🧩'},word:{title:'Descoperă cuvântul',subtitle:'Găsește cuvântul norvegian folosind indiciile.',icon:'🔤'}};

const makeQuiz=(lessons,difficulty)=>{
  const pool=lessons.flatMap((lesson)=>lesson.vocabulary.map(([word,translation,example],index)=>({id:`q-${lesson.id}-${index}`,lessonId:lesson.id,prompt:difficulty==='hard'?`Scrie în norvegiană: „${translation}”`:`Ce înseamnă „${word}”?`,answer:difficulty==='hard'?word:translation,word,example,type:difficulty==='hard'?'text':'choice'})));
  return pool.map((item)=>item.type==='choice'?{...item,options:shuffle([item.answer,...shuffle(pool.filter((other)=>other.answer!==item.answer).map((other)=>other.answer)).slice(0,difficulty==='easy'?2:3)])}:item);
};
const makeOrder=(lessons)=>lessons.flatMap((lesson)=>[
  ...lesson.exercises.filter((exercise)=>exercise.type==='order').map((exercise,index)=>({id:`o-${lesson.id}-${index}`,lessonId:lesson.id,prompt:exercise.prompt,answer:exercise.answer.join(' '),words:shuffle(exercise.answer),explanation:exercise.explanation,type:'order'})),
  ...lesson.dialogue.map((line,index)=>({id:`d-${lesson.id}-${index}`,lessonId:lesson.id,prompt:`Construiește: „${line[2]}”`,answer:line[1].replace(/[.!?]/g,''),words:shuffle(line[1].replace(/[.!?]/g,'').split(' ')),explanation:`Forma corectă este „${line[1]}”`,type:'order'})),
]);
const makeWords=(lessons)=>lessons.flatMap((lesson)=>lesson.vocabulary.map(([word,translation,example],index)=>({id:`w-${lesson.id}-${index}`,lessonId:lesson.id,prompt:translation,answer:word,example,type:'word'})));

const saveReview=(item)=>saveReviewItem({level:localStorage.getItem('norwegian_active_level')||'A1',lessonId:item.lessonId,source:'practice',prompt:item.prompt,answer:item.answer});

const PracticeGame=({game})=>{
  const info=gameInfo[game];
  const availableLessons=courseLessons;
  const[screen,setScreen]=useState('setup');const[lessonFilter,setLessonFilter]=useState('unlocked');const[difficulty,setDifficulty]=useState('normal');const[length,setLength]=useState(5);const[questions,setQuestions]=useState([]);const[current,setCurrent]=useState(0);const[answer,setAnswer]=useState('');const[selected,setSelected]=useState([]);const[checked,setChecked]=useState(false);const[results,setResults]=useState([]);const[hint,setHint]=useState(false);
  const question=questions[current];
  const selectedLessons=useMemo(()=>lessonFilter==='unlocked'?availableLessons:courseLessons.filter((lesson)=>lesson.id===Number(lessonFilter)),[lessonFilter,availableLessons]);
  const start=()=>{let pool=game==='quiz'?makeQuiz(selectedLessons,difficulty):game==='order'?makeOrder(selectedLessons):makeWords(selectedLessons);pool=shuffle(pool);if(!pool.length)return;setQuestions(pool.slice(0,Math.min(length,pool.length)));setCurrent(0);setResults([]);setAnswer('');setSelected([]);setChecked(false);setHint(false);setScreen('game')};
  const normalized=(value)=>value.trim().toLocaleLowerCase('nb-NO').replace(/[.!?]/g,'');
  const isCorrect=()=>{if(game==='order')return normalized(selected.join(' '))===normalized(question.answer);return normalized(answer)===normalized(question.answer)};
  const verify=()=>{if(checked||(!answer&&!selected.length))return;const correct=isCorrect();setChecked(true);setResults((all)=>[...all,{question,correct,given:game==='order'?selected.join(' '):answer}]);if(!correct)saveReview(question)};
  const next=()=>{if(current===questions.length-1){setScreen('result');return}setCurrent((value)=>value+1);setAnswer('');setSelected([]);setChecked(false);setHint(false)};
  const restartMistakes=()=>{const mistakes=results.filter((result)=>!result.correct).map((result)=>result.question);if(!mistakes.length){setScreen('setup');return}setQuestions(mistakes);setCurrent(0);setResults([]);setAnswer('');setSelected([]);setChecked(false);setHint(false);setScreen('game')};
  const score=results.filter((result)=>result.correct).length;

  if(screen==='setup')return <div className="practice-game"><Link className="practice-back" to="/invata#practica">← Înapoi la curs</Link><header className="practice-game__hero"><span role="img" aria-hidden="true">{info.icon}</span><div><p>Practică suplimentară</p><h1>{info.title}</h1><small>{info.subtitle}</small></div></header><div className="game-setup"><section><h2>Ce vrei să repeți?</h2><div className="setup-options"><button className={lessonFilter==='unlocked'?'active':''} onClick={()=>setLessonFilter('unlocked')}>Toate lecțiile deblocate<small>{availableLessons.length} lecții disponibile</small></button>{availableLessons.map((lesson)=><button className={lessonFilter===String(lesson.id)?'active':''} onClick={()=>setLessonFilter(String(lesson.id))} key={lesson.id}>Lecția {lesson.id}<small>{lesson.title}</small></button>)}</div></section>{game==='quiz'&&<section><h2>Dificultate</h2><div className="difficulty-options">{[['easy','Ușor','Variante de răspuns'],['normal','Normal','Vocabular amestecat'],['hard','Dificil','Scriere fără variante']].map(([value,label,desc])=><button className={difficulty===value?'active':''} onClick={()=>setDifficulty(value)} key={value}><strong>{label}</strong><small>{desc}</small></button>)}</div></section>}<section><h2>Lungimea sesiunii</h2><div className="length-options">{[5,10,15].map((value)=><button className={length===value?'active':''} onClick={()=>setLength(value)} key={value}>{value} întrebări</button>)}</div></section><button className="start-game" onClick={start}>Începe sesiunea →</button></div></div>;

  if(screen==='result')return <div className="practice-game"><div className="game-result"><div className="game-result__icon">✓</div><p>Sesiune finalizată</p><h1>{score} din {results.length} răspunsuri corecte</h1><div className="game-result__score">{Math.round((score/results.length)*100)}%</div>{score<results.length&&<div className="mistake-summary"><h2>De repetat</h2>{results.filter((result)=>!result.correct).map((result)=><div key={result.question.id}><span>{result.question.prompt}</span><strong>{result.question.answer}</strong></div>)}</div>}<div className="game-result__actions">{score<results.length&&<button className="primary" onClick={restartMistakes}>Repetă greșelile</button>}<button onClick={()=>setScreen('setup')}>Sesiune nouă</button><Link to="/invata#practica">Înapoi la curs</Link></div></div></div>;

  const correct=checked&&isCorrect();
  return <div className="practice-game practice-game--session"><header className="session-header"><button onClick={()=>setScreen('setup')} aria-label="Închide sesiunea">×</button><div><span style={{width:`${((current+(checked?1:0))/questions.length)*100}%`}}/></div><strong>{current+1}/{questions.length}</strong></header><main className="game-question"><p className="question-meta">Lecția {question.lessonId} · {info.title}</p><h1>{game==='word'?'Descoperă cuvântul':question.prompt}</h1>{game==='word'&&<><div className="word-clue"><small>Traducere</small><strong>{question.prompt}</strong><span>{question.answer.split('').map((char,index)=><i key={index}>{hint&&index===0?char:'_'}</i>)}</span><p>{question.example.replace(new RegExp(question.answer,'i'),'_____')}</p></div><button className="hint-button" onClick={()=>setHint(true)} disabled={hint}>Arată prima literă</button></>}{game==='quiz'&&question.type==='choice'&&<div className="game-choices">{question.options.map((option)=><button disabled={checked} className={answer===option?'selected':''} onClick={()=>setAnswer(option)} key={option}>{option}</button>)}</div>}{((game==='quiz'&&question.type==='text')||game==='word')&&<input className="game-input" disabled={checked} value={answer} onChange={(event)=>setAnswer(event.target.value)} onKeyDown={(event)=>event.key==='Enter'&&verify()} placeholder="Scrie răspunsul"/>}{game==='order'&&<><div className="order-zone">{selected.length?selected.map((word,index)=><button disabled={checked} onClick={()=>setSelected((all)=>all.filter((_,i)=>i!==index))} key={`${word}-${index}`}>{word}</button>):<span>Selectează cuvintele în ordinea corectă</span>}</div><div className="order-bank">{question.words.map((word,index)=><button disabled={checked||selected.filter((selectedWord)=>selectedWord===word).length>=question.words.slice(0,index+1).filter((candidate)=>candidate===word).length} onClick={()=>setSelected((all)=>[...all,word])} key={`${word}-${index}`}>{word}</button>)}</div></>}{checked&&<div className={`game-feedback ${correct?'correct':'wrong'}`}><h2>{correct?'Corect!':'Nu este încă corect.'}</h2><p>{correct?(question.example||question.explanation||'Foarte bine!'):`Răspunsul corect este: ${question.answer}`}</p>{game==='word'&&<button onClick={()=>speakNorwegian(question.answer)}>🔊 Ascultă pronunția</button>}</div>}</main><footer className="session-actions">{!checked?<button className="primary" onClick={verify} disabled={!answer&&!selected.length}>Verifică</button>:<button className="primary" onClick={next}>{current===questions.length-1?'Vezi rezultatul':'Continuă →'}</button>}</footer></div>;
};
export default PracticeGame;
