export const a1ExtraLessons = [
  {
    id: 6, title: 'Familie și persoane', duration: 22,
    objectives: ['să vorbești despre familia ta', 'să folosești forme articulate simple', 'să exprimi posesia cu „min” și „din”'],
    vocabulary: [
      ['En familie', 'O familie', 'Jeg har en familie.', 'Am o familie.'],
      ['En bror', 'Un frate', 'Broren min bor i Oslo.', 'Fratele meu locuiește în Oslo.'],
      ['En søster', 'O soră', 'Søsteren min heter Maria.', 'Sora mea se numește Maria.'],
      ['Foreldre', 'Părinți', 'Foreldrene mine bor i Romania.', 'Părinții mei locuiesc în România.'],
      ['Gammel', 'În vârstă / vechi', 'Hvor gammel er broren din?', 'Câți ani are fratele tău?'],
      ['Snill', 'Amabil', 'Søsteren min er snill.', 'Sora mea este amabilă.'],
    ],
    dialogue: [
      ['Erik', 'Har du en bror eller en søster?', 'Ai un frate sau o soră?'],
      ['Ana', 'Ja, jeg har en bror.', 'Da, am un frate.'],
      ['Erik', 'Hvor bor broren din?', 'Unde locuiește fratele tău?'],
      ['Ana', 'Broren min bor i Oslo.', 'Fratele meu locuiește în Oslo.'],
    ],
    grammar: {
      title: 'Forme articulate și posesive',
      rule: 'Spunem „broren min” sau „min bror”. Când posesivul vine după substantiv, substantivul este articulat: broren min, søsteren din.',
      examples: ['Broren min bor i Oslo. — Fratele meu locuiește în Oslo.', 'Hva heter søsteren din? — Cum o cheamă pe sora ta?'],
      wrong: 'Min broren bor i Oslo.',
    },
    exercises: [
      { type:'choice', prompt:'Care variantă înseamnă „fratele meu”?', options:['Broren min','Bror din','Min broren'], answer:0, explanation:'Forma naturală este „broren min”.' },
      { type:'fill', prompt:'Completează: „Søsteren ___ heter Maria.”', answer:'min', explanation:'„Søsteren min” înseamnă „sora mea”.' },
      { type:'order', prompt:'Construiește „Părinții mei locuiesc în România”.', words:['i Romania','mine','bor','Foreldrene'], answer:['Foreldrene','mine','bor','i Romania'], explanation:'Posesivul urmează forma articulată „foreldrene”.' },
    ],
  },
  {
    id: 7, title: 'Timp, zile și întâlniri', duration: 23,
    objectives: ['să spui ziua și ora', 'să stabilești o întâlnire', 'să folosești verbul pe poziția a doua'],
    vocabulary: [
      ['I dag', 'Astăzi', 'I dag jobber jeg hjemme.', 'Astăzi lucrez acasă.'],
      ['I morgen', 'Mâine', 'Vi møtes i morgen.', 'Ne întâlnim mâine.'],
      ['Mandag', 'Luni', 'Vi møtes på mandag.', 'Ne întâlnim luni.'],
      ['Klokka', 'Ora', 'Møtet er klokka ni.', 'Întâlnirea este la ora nouă.'],
      ['Vi møtes', 'Ne întâlnim', 'Vi møtes på mandag.', 'Ne întâlnim luni.'],
      ['Passer det?', 'Este potrivit?', 'Passer det klokka seks?', 'Este potrivit la ora șase?'],
    ],
    dialogue: [
      ['Ana', 'Vi møtes på mandag.', 'Ne întâlnim luni.'],
      ['Lars', 'Ja. Passer klokka seks?', 'Da. Este potrivit la ora șase?'],
      ['Ana', 'Ja, klokka seks passer.', 'Da, ora șase este potrivită.'],
      ['Lars', 'Ja, vi møtes klokka seks.', 'Da, ne întâlnim la ora șase.'],
    ],
    grammar: {
      title: 'Verbul pe poziția a doua',
      rule: 'În propoziția principală, verbul ocupă poziția a doua. Dacă începem cu timpul, verbul vine înaintea persoanei.',
      examples: ['Jeg jobber i dag. — Lucrez astăzi.', 'I dag jobber jeg. — Astăzi lucrez.'],
      wrong: 'I dag jeg jobber.',
    },
    exercises: [
      { type:'choice', prompt:'Cum spui „mâine”?', options:['I dag','I morgen','Mandag'], answer:1, explanation:'„I morgen” înseamnă „mâine”.' },
      { type:'fill', prompt:'Completează: „Vi møtes ___ mandag.”', answer:'på', explanation:'Cu zilele săptămânii folosim „på”.' },
      { type:'order', prompt:'Construiește „Astăzi lucrez acasă”.', words:['hjemme','jobber','I dag','jeg'], answer:['I dag','jobber','jeg','hjemme'], explanation:'După „I dag”, verbul „jobber” ocupă poziția a doua.' },
    ],
  },
  {
    id: 8, title: 'Vreme și îmbrăcăminte', duration: 24,
    objectives: ['să descrii vremea', 'să spui ce haine îți trebuie', 'să folosești construcția „det er”'],
    vocabulary: [
      ['Vær', 'Vreme', 'Hvordan er været i dag?', 'Cum este vremea astăzi?'],
      ['Det regner', 'Plouă', 'Det regner i dag.', 'Plouă astăzi.'],
      ['Kaldt', 'Rece', 'Det er kaldt ute.', 'Este frig afară.'],
      ['Varmt', 'Cald', 'Det er varmt inne.', 'Este cald înăuntru.'],
      ['En jakke', 'O geacă', 'Jeg trenger en varm jakke.', 'Am nevoie de o geacă groasă.'],
      ['En paraply', 'O umbrelă', 'Jeg har en paraply.', 'Am o umbrelă.'],
    ],
    dialogue: [
      ['Mia', 'Hvordan er været i dag?', 'Cum este vremea astăzi?'],
      ['Dan', 'Det er kaldt og det regner.', 'Este frig și plouă.'],
      ['Mia', 'Jeg trenger en varm jakke.', 'Am nevoie de o geacă groasă.'],
      ['Dan', 'Ja, og jeg har en paraply.', 'Da, iar eu am o umbrelă.'],
    ],
    grammar: {
      title: 'Construcția „det er”',
      rule: 'Pentru vreme și descrieri simple folosim „det er” urmat de un adjectiv: det er kaldt, varmt sau fint.',
      examples: ['Det er kaldt ute. — Este frig afară.', 'Det er varmt inne. — Este cald înăuntru.'],
      wrong: 'Det kaldt er ute.',
    },
    exercises: [
      { type:'choice', prompt:'Cum spui „Este frig afară”?', options:['Det er kaldt ute.','Det har kaldt ute.','Kaldt det ute.'], answer:0, explanation:'Descrierea vremii începe cu „det er”.' },
      { type:'fill', prompt:'Completează: „Det ___ varmt inne.”', answer:'er', explanation:'Construcția corectă este „det er”.' },
      { type:'order', prompt:'Construiește „Am nevoie de o geacă”.', words:['en jakke','trenger','Jeg'], answer:['Jeg','trenger','en jakke'], explanation:'Folosim formula simplă „Jeg trenger...”.' },
    ],
  },
  {
    id: 9, title: 'Drumuri și transport', duration: 25,
    objectives: ['să ceri indicații', 'să înțelegi direcții de bază', 'să cumperi un bilet simplu'],
    vocabulary: [
      ['Til høyre', 'La dreapta', 'Ta til høyre.', 'Fă dreapta.'],
      ['Til venstre', 'La stânga', 'Ta til venstre.', 'Fă stânga.'],
      ['Rett frem', 'Drept înainte', 'Gå rett frem.', 'Mergi drept înainte.'],
      ['En buss', 'Un autobuz', 'Bussen går til sentrum.', 'Autobuzul merge spre centru.'],
      ['Et tog', 'Un tren', 'Toget går klokka åtte.', 'Trenul pleacă la ora opt.'],
      ['En billett', 'Un bilet', 'Jeg vil ha en billett til Oslo.', 'Doresc un bilet spre Oslo.'],
    ],
    dialogue: [
      ['Ana', 'Unnskyld, hvor er bussen til Oslo?', 'Scuzați-mă, unde este autobuzul spre Oslo?'],
      ['Ola', 'Gå rett frem og ta til venstre.', 'Mergeți drept înainte și faceți stânga.'],
      ['Ana', 'Takk. Jeg vil ha en billett til Oslo.', 'Mulțumesc. Doresc un bilet spre Oslo.'],
      ['Ola', 'En billett koster 40 kroner.', 'Un bilet costă 40 de coroane.'],
    ],
    grammar: {
      title: 'Imperativul pentru instrucțiuni',
      rule: 'Pentru o instrucțiune scurtă folosim verbul fără „å”: gå, ta, vent și stopp.',
      examples: ['Gå rett frem! — Mergi drept înainte!', 'Ta til venstre! — Fă stânga!'],
      wrong: 'Å gå rett frem!',
    },
    exercises: [
      { type:'choice', prompt:'Ce înseamnă „til venstre”?', options:['La dreapta','La stânga','Drept înainte'], answer:1, explanation:'„Til venstre” înseamnă „la stânga”.' },
      { type:'fill', prompt:'Completează: „___ rett frem!”', answer:'Gå', explanation:'Imperativul verbului „å gå” este „gå”.' },
      { type:'order', prompt:'Construiește „Doresc un bilet spre Oslo”.', words:['til Oslo','en billett','vil ha','Jeg'], answer:['Jeg','vil ha','en billett','til Oslo'], explanation:'Reutilizăm formula cunoscută „Jeg vil ha...”.' },
    ],
  },
  {
    id: 10, title: 'O zi întreagă în norvegiană', duration: 30,
    objectives: ['să reutilizezi vocabularul nivelului A1', 'să treci prin mai multe conversații scurte', 'să observi cât de multe formule cunoști deja'],
    vocabulary: [
      ['Hvordan har du det?', 'Cum te simți?', 'Hei! Hvordan har du det?', 'Salut! Cum te simți?'],
      ['Jeg vil ha', 'Doresc', 'Jeg vil ha en kaffe.', 'Doresc o cafea.'],
      ['Hvor mye koster det?', 'Cât costă?', 'Hvor mye koster det?', 'Cât costă?'],
      ['Jeg jobber ikke hjemme', 'Nu lucrez acasă', 'I dag jobber jeg ikke hjemme.', 'Astăzi nu lucrez acasă.'],
      ['Vi møtes klokka seks', 'Ne întâlnim la ora șase', 'Vi møtes klokka seks.', 'Ne întâlnim la ora șase.'],
      ['Gå rett frem', 'Mergi drept înainte', 'Gå rett frem og ta til venstre.', 'Mergi drept înainte și fă stânga.'],
    ],
    dialogue: [
      ['Lars', 'Hei! Hvordan har du det?', 'Salut! Cum te simți?'],
      ['Ana', 'Bra, takk. I dag jobber jeg ikke hjemme.', 'Bine, mulțumesc. Astăzi nu lucrez acasă.'],
      ['Lars', 'Vil du ha en kaffe klokka seks?', 'Dorești o cafea la ora șase?'],
      ['Ana', 'Ja, takk. Vi møtes klokka seks.', 'Da, mulțumesc. Ne întâlnim la ora șase.'],
    ],
    grammar: {
      title: 'Recapitulare: construiește propoziția',
      rule: 'Pornește cu o formulă cunoscută, păstrează verbul pe poziția a doua și adaugă timpul sau locul la final.',
      examples: ['Jeg jobber hjemme i dag. — Lucrez acasă astăzi.', 'I dag jobber jeg hjemme. — Astăzi lucrez acasă.'],
      wrong: 'I dag jeg jobber hjemme.',
    },
    exercises: [
      { type:'choice', prompt:'Care este răspunsul potrivit la „Hvordan har du det?”', options:['Bra, takk.','Til venstre.','En kvittering.'], answer:0, explanation:'„Bra, takk” este răspunsul scurt învățat în prima lecție.' },
      { type:'fill', prompt:'Completează: „Jeg vil ___ en kaffe.”', answer:'ha', explanation:'Reutilizăm formula „Jeg vil ha...”.' },
      { type:'order', prompt:'Construiește „Astăzi nu lucrez acasă”.', words:['hjemme','ikke','jobber','I dag','jeg'], answer:['I dag','jobber','jeg','ikke','hjemme'], explanation:'După timpul pus primul, verbul rămâne pe poziția a doua.' },
    ],
  },
];
