export const a2Lessons = [
  {
    id: 1, title: 'În oraș și cu transportul', duration: 24,
    objectives: ['să ceri informații despre transport', 'să explici o întârziere', 'să înțelegi indicații simple de călătorie'],
    vocabulary: [
      ['En holdeplass', 'O stație', 'Bussen stopper ved neste holdeplass.', 'Autobuzul oprește la următoarea stație.'],
      ['Å rekke', 'A prinde / a ajunge la timp', 'Rekker vi toget klokka åtte?', 'Prindem trenul de la ora opt?', 'Rekker'],
      ['Forsinket', 'Întârziat', 'Toget er tjue minutter forsinket.', 'Trenul are o întârziere de douăzeci de minute.'],
      ['Å bytte', 'A schimba', 'Du må bytte buss i sentrum.', 'Trebuie să schimbi autobuzul în centru.'],
      ['En billett', 'Un bilet', 'Kan jeg kjøpe en billett her?', 'Pot cumpăra un bilet aici?'],
      ['Neste', 'Următorul', 'Når går neste tog til Bergen?', 'Când pleacă următorul tren spre Bergen?'],
    ],
    dialogue: [
      ['Mara', 'Unnskyld, går denne bussen til sentrum?', 'Scuzați-mă, acest autobuz merge în centru?'],
      ['Sjåfør', 'Ja, men du må bytte ved Nationaltheatret.', 'Da, dar trebuie să schimbați la Nationaltheatret.'],
      ['Mara', 'Rekker jeg toget som går klokka ni?', 'Prind trenul care pleacă la ora nouă?'],
      ['Sjåfør', 'Ja, hvis bussen ikke blir forsinket.', 'Da, dacă autobuzul nu întârzie.'],
    ],
    grammar: { title: 'Verbe modale + infinitiv', rule: 'După „må”, „kan”, „skal” și „vil”, verbul următor apare fără marcatorul „å”.', examples: ['Du må bytte buss. — Trebuie să schimbi autobuzul.', 'Kan jeg kjøpe billett? — Pot cumpăra bilet?'], wrong: 'Du må å bytte buss.' },
    exercises: [
      { type: 'choice', prompt: 'Ce înseamnă „forsinket”?', options: ['Anulat', 'Întârziat', 'Aglomerat'], answer: 1, explanation: '„Forsinket” descrie ceva care ajunge sau pleacă mai târziu.' },
      { type: 'fill', prompt: 'Completează: „Du må ___ buss i sentrum.”', answer: 'bytte', explanation: 'După „må” folosim infinitivul fără „å”.' },
      { type: 'order', prompt: 'Construiește „Când pleacă următorul tren?”', words: ['neste', 'går', 'Når', 'tog'], answer: ['Når', 'går', 'neste', 'tog'], explanation: 'În întrebare, verbul apare imediat după cuvântul interogativ.' },
    ],
  },
  {
    id: 2, title: 'La medic și la farmacie', duration: 26,
    objectives: ['să descrii simptome comune', 'să ceri o programare', 'să înțelegi recomandări medicale simple'],
    vocabulary: [
      ['En time', 'O programare', 'Jeg vil gjerne bestille en time hos legen.', 'Aș dori să fac o programare la medic.'],
      ['Et symptom', 'Un simptom', 'Hvilke symptomer har du?', 'Ce simptome ai?'],
      ['En resept', 'O rețetă', 'Legen skrev ut en resept.', 'Medicul a eliberat o rețetă.'],
      ['Vondt', 'Durere / dureros', 'Jeg har vondt i halsen.', 'Mă doare gâtul.'],
      ['Forkjølet', 'Răcit', 'Jeg har vært forkjølet i tre dager.', 'Sunt răcit de trei zile.'],
      ['Å bli bedre', 'A se simți mai bine', 'Jeg håper du blir bedre snart.', 'Sper să te simți mai bine în curând.', 'blir bedre'],
    ],
    dialogue: [
      ['Pasient', 'Hei, jeg vil gjerne bestille en time.', 'Bună, aș dori să fac o programare.'],
      ['Sekretær', 'Hva gjelder det?', 'Despre ce este vorba?'],
      ['Pasient', 'Jeg har feber og vondt i halsen.', 'Am febră și mă doare gâtul.'],
      ['Sekretær', 'Legen kan se deg i morgen formiddag.', 'Medicul vă poate consulta mâine dimineață.'],
    ],
    grammar: { title: 'Durată cu „i”', rule: 'Pentru o acțiune sau stare care continuă, norvegiana folosește adesea perfectul împreună cu „i” + perioadă.', examples: ['Jeg har vært syk i to dager. — Sunt bolnav de două zile.', 'Hun har ventet i en time. — Așteaptă de o oră.'], wrong: 'Jeg er syk siden to dager.' },
    exercises: [
      { type: 'choice', prompt: 'Cum spui că te doare gâtul?', options: ['Jeg har vondt i halsen.','Jeg er halsen.','Jeg får resept.'], answer: 0, explanation: 'Structura „ha vondt i” este folosită pentru durere.' },
      { type: 'fill', prompt: 'Completează: „Jeg har vært forkjølet ___ tre dager.”', answer: 'i', explanation: '„I” introduce durata unei stări care continuă.' },
      { type: 'order', prompt: 'Construiește „Ce simptome ai?”', words: ['du', 'har', 'symptomer', 'Hvilke'], answer: ['Hvilke', 'symptomer', 'har', 'du'], explanation: 'Substantivul urmează după „hvilke”, apoi verbul și subiectul.' },
    ],
  },
  {
    id: 3, title: 'Planuri și timp liber', duration: 24,
    objectives: ['să vorbești despre obiceiuri', 'să inviți pe cineva', 'să formulezi planuri de viitor'],
    vocabulary: [
      ['Å glede seg', 'A aștepta cu nerăbdare', 'Jeg gleder meg til helgen.', 'Aștept cu nerăbdare weekendul.', 'gleder meg'],
      ['Pleier å', 'Obișnuiesc să', 'Vi pleier å gå på tur på søndager.', 'Obișnuim să mergem în drumeție duminica.'],
      ['Kanskje', 'Poate', 'Kanskje vi kan møtes etter jobb.', 'Poate ne putem întâlni după serviciu.'],
      ['En tur', 'O plimbare / drumeție', 'Skal vi ta en tur i skogen?', 'Mergem la o plimbare prin pădure?'],
      ['Å invitere', 'A invita', 'Hun inviterer vennene sine på middag.', 'Ea își invită prietenii la cină.', 'inviterer'],
      ['Å passe', 'A fi convenabil', 'Passer det for deg på lørdag?', 'Îți convine sâmbătă?', 'Passer'],
    ],
    dialogue: [
      ['Erik', 'Har du noen planer for helgen?', 'Ai planuri pentru weekend?'],
      ['Mara', 'Jeg tenkte å gå en tur i marka.', 'Mă gândeam să fac o drumeție în pădure.'],
      ['Erik', 'Kan jeg bli med?', 'Pot să vin și eu?'],
      ['Mara', 'Selvfølgelig! Passer det klokka ti?', 'Desigur! Îți convine la ora zece?'],
    ],
    grammar: { title: 'Viitorul: „skal” și „kommer til å”', rule: 'Folosește „skal” pentru planuri și intenții, iar „kommer til å” pentru previziuni.', examples: ['Jeg skal besøke Oslo. — Voi vizita Oslo.', 'Det kommer til å regne. — Probabil va ploua.'], wrong: 'Jeg skal å besøke Oslo.' },
    exercises: [
      { type: 'choice', prompt: 'Ce exprimă „Jeg gleder meg til helgen”?', options: ['Regret weekendul','Aștept weekendul cu nerăbdare','Lucrez în weekend'], answer: 1, explanation: '„Å glede seg til” exprimă anticipare pozitivă.' },
      { type: 'fill', prompt: 'Completează: „Vi ___ å gå på tur.”', answer: 'pleier', explanation: '„Pleier å” descrie un obicei.' },
      { type: 'order', prompt: 'Construiește „Îți convine sâmbătă?”', words: ['lørdag', 'deg', 'det', 'for', 'Passer'], answer: ['Passer', 'det', 'for', 'deg', 'lørdag'], explanation: 'Întrebarea începe cu verbul „Passer”.' },
    ],
  },
  {
    id: 4, title: 'Locuință și vecini', duration: 27,
    objectives: ['să discuți despre închiriere', 'să semnalezi o problemă în locuință', 'să vorbești politicos cu vecinii'],
    vocabulary: [
      ['Å leie', 'A închiria', 'Vi leier en leilighet nær sentrum.', 'Închiriem un apartament aproape de centru.'],
      ['Et depositum', 'O garanție', 'Depositumet tilsvarer tre måneders husleie.', 'Garanția este echivalentă cu trei luni de chirie.'],
      ['En nabo', 'Un vecin', 'Naboen vår er veldig hjelpsom.', 'Vecinul nostru este foarte săritor.'],
      ['Støy', 'Zgomot', 'Det er mye støy om kvelden.', 'Este mult zgomot seara.'],
      ['Å reparere', 'A repara', 'Utleieren skal reparere ovnen.', 'Proprietarul va repara cuptorul.'],
      ['Å flytte', 'A se muta', 'Vi skal flytte neste måned.', 'Ne vom muta luna viitoare.'],
    ],
    dialogue: [
      ['Leietaker', 'Hei, ovnen på kjøkkenet virker ikke.', 'Bună, cuptorul din bucătărie nu funcționează.'],
      ['Utleier', 'Takk for at du sa fra.', 'Mulțumesc că m-ai anunțat.'],
      ['Leietaker', 'Når kan den bli reparert?', 'Când poate fi reparat?'],
      ['Utleier', 'Jeg sender noen i morgen ettermiddag.', 'Trimit pe cineva mâine după-amiază.'],
    ],
    grammar: { title: 'Propoziții relative cu „som”', rule: '„Som” leagă informații despre o persoană sau un lucru și poate însemna „care”.', examples: ['Mannen som bor her, er hyggelig. — Bărbatul care locuiește aici este amabil.', 'Ovnen som er ødelagt, må repareres. — Cuptorul care este stricat trebuie reparat.'], wrong: 'Mannen hvilken bor her.' },
    exercises: [
      { type: 'choice', prompt: 'Ce este „et depositum”?', options: ['O factură','O garanție','Un contract'], answer: 1, explanation: 'Depozitul este suma oferită ca garanție la închiriere.' },
      { type: 'fill', prompt: 'Completează: „Naboen ___ bor ovenpå, er hyggelig.”', answer: 'som', explanation: '„Som” introduce propoziția relativă.' },
      { type: 'order', prompt: 'Construiește „Ne mutăm luna viitoare.”', words: ['måned', 'flytte', 'Vi', 'neste', 'skal'], answer: ['Vi', 'skal', 'flytte', 'neste', 'måned'], explanation: 'Planul se formează cu „skal” + infinitiv.' },
    ],
  },
  {
    id: 5, title: 'Experiențe și trecut', duration: 28,
    objectives: ['să povestești ce ai făcut', 'să diferențiezi trecutul simplu de perfect', 'să descrii experiențe personale'],
    vocabulary: [
      ['I går', 'Ieri', 'I går besøkte vi Norsk Folkemuseum.', 'Ieri am vizitat Muzeul Norvegian de Istorie Culturală.'],
      ['Besøkte', 'Am vizitat', 'Hun besøkte familien sin i helgen.', 'Ea și-a vizitat familia în weekend.'],
      ['Har vært', 'Am fost', 'Jeg har vært i Tromsø flere ganger.', 'Am fost în Tromsø de mai multe ori.'],
      ['Opplevde', 'Am trăit / experimentat', 'Vi opplevde nordlyset for første gang.', 'Am văzut aurora boreală pentru prima dată.'],
      ['Siden', 'De când', 'Jeg har bodd her siden 2024.', 'Locuiesc aici din 2024.'],
      ['Allerede', 'Deja', 'De har allerede sett filmen.', 'Ei au văzut deja filmul.'],
    ],
    dialogue: [
      ['Lars', 'Har du noen gang vært i Nord-Norge?', 'Ai fost vreodată în nordul Norvegiei?'],
      ['Mara', 'Ja, jeg reiste til Tromsø i fjor.', 'Da, am călătorit la Tromsø anul trecut.'],
      ['Lars', 'Så du nordlyset?', 'Ai văzut aurora boreală?'],
      ['Mara', 'Ja, det var en opplevelse jeg aldri glemmer.', 'Da, a fost o experiență pe care nu o voi uita niciodată.'],
    ],
    grammar: { title: 'Preterit sau perfect?', rule: 'Folosește preteritul cu un moment trecut încheiat și perfectul pentru experiențe sau rezultate relevante acum.', examples: ['Jeg reiste i fjor. — Am călătorit anul trecut.', 'Jeg har vært i Tromsø. — Am fost în Tromsø.'], wrong: 'Jeg har reist i fjor.' },
    exercises: [
      { type: 'choice', prompt: 'Care propoziție este corectă cu „i fjor”?', options: ['Jeg har reist i fjor.','Jeg reiste i fjor.','Jeg reiser i fjor.'], answer: 1, explanation: 'Un moment trecut încheiat cere preteritul.' },
      { type: 'fill', prompt: 'Completează: „Jeg har bodd her ___ 2024.”', answer: 'siden', explanation: '„Siden” indică momentul de început.' },
      { type: 'order', prompt: 'Construiește „Am fost în Tromsø.”', words: ['Tromsø', 'vært', 'Jeg', 'i', 'har'], answer: ['Jeg', 'har', 'vært', 'i', 'Tromsø'], explanation: 'Perfectul se formează cu „har” + participiu.' },
    ],
  },
];
