export const a2Lessons = [
  {
    id: 1, title: 'Planuri și invitații', duration: 24,
    objectives: ['să inviți o persoană la o activitate', 'să accepți sau să refuzi politicos', 'să stabilești ziua și ora'],
    vocabulary: [
      ['Har du lyst til...?', 'Ai chef să...?', 'Har du lyst til å ta en kaffe?', 'Ai chef să bem o cafea?', 'lyst'],
      ['Å bli med', 'A veni împreună cu cineva', 'Vil du bli med på tur?', 'Vrei să vii cu noi la plimbare?', 'bli med'],
      ['På lørdag', 'Sâmbătă', 'Vi møtes på lørdag.', 'Ne întâlnim sâmbătă.'],
      ['Etter jobb', 'După serviciu', 'Vi kan møtes etter jobb.', 'Ne putem întâlni după serviciu.'],
      ['Det passer', 'Este potrivit', 'Klokka seks passer for meg.', 'Ora șase este potrivită pentru mine.', 'passer'],
      ['Jeg gleder meg', 'Abia aștept', 'Jeg gleder meg til lørdag.', 'Abia aștept ziua de sâmbătă.', 'gleder meg'],
    ],
    dialogue: [
      ['Anna', 'Har du lyst til å ta en kaffe etter jobb?', 'Ai chef să bem o cafea după serviciu?'],
      ['Lars', 'Ja, gjerne. Når passer det?', 'Da, cu plăcere. Când este potrivit?'],
      ['Anna', 'Passer klokka seks?', 'Este potrivit la ora șase?'],
      ['Lars', 'Ja, det passer. Jeg gleder meg!', 'Da, este potrivit. Abia aștept!'],
    ],
    grammar: {
      title: 'Planuri cu „skal” și propuneri cu „kan”',
      rule: 'Folosim „skal” pentru un plan stabilit și „kan” pentru o posibilitate sau propunere. După ele, verbul apare fără „å”.',
      examples: ['Vi skal møtes på lørdag. — Ne vom întâlni sâmbătă.', 'Vi kan møtes etter jobb. — Ne putem întâlni după serviciu.'],
      wrong: 'Vi skal å møtes på lørdag.',
    },
    exercises: [
      { type: 'choice', prompt: 'Cum accepți politicos o invitație?', options: ['Ja, gjerne.', 'Jeg er en kaffe.', 'Til venstre.'], answer: 0, explanation: '„Ja, gjerne” înseamnă „Da, cu plăcere”.' },
      { type: 'fill', prompt: 'Completează: „Vi skal ___ på lørdag.”', answer: 'møtes', explanation: 'După „skal” folosim verbul fără „å”.' },
      { type: 'order', prompt: 'Construiește „Ne putem întâlni după serviciu”.', words: ['etter jobb', 'møtes', 'Vi', 'kan'], answer: ['Vi', 'kan', 'møtes', 'etter jobb'], explanation: 'Ordinea este subiect + „kan” + verb + timp.' },
    ],
  },
  {
    id: 2, title: 'Transport și întârzieri', duration: 25,
    objectives: ['să întrebi despre următoarea plecare', 'să înțelegi când trebuie să schimbi mijlocul de transport', 'să explici simplu o întârziere'],
    vocabulary: [
      ['En holdeplass', 'O stație', 'Bussen stopper ved neste holdeplass.', 'Autobuzul oprește la următoarea stație.'],
      ['Neste', 'Următorul / următoarea', 'Når går neste tog?', 'Când pleacă următorul tren?'],
      ['Forsinket', 'Întârziat', 'Toget er ti minutter forsinket.', 'Trenul are o întârziere de zece minute.'],
      ['Å bytte', 'A schimba', 'Du må bytte buss i sentrum.', 'Trebuie să schimbi autobuzul în centru.', 'bytte'],
      ['Å rekke', 'A ajunge la timp', 'Rekker vi toget klokka åtte?', 'Prindem trenul de la ora opt?', 'Rekker'],
      ['En avgang', 'O plecare', 'Neste avgang er klokka ni.', 'Următoarea plecare este la ora nouă.'],
    ],
    dialogue: [
      ['Ana', 'Unnskyld, når går neste buss til sentrum?', 'Scuzați-mă, când pleacă următorul autobuz spre centru?'],
      ['Ola', 'Den går om ti minutter.', 'Pleacă peste zece minute.'],
      ['Ana', 'Må jeg bytte buss?', 'Trebuie să schimb autobuzul?'],
      ['Ola', 'Nei, men bussen er litt forsinket.', 'Nu, dar autobuzul este puțin întârziat.'],
    ],
    grammar: {
      title: 'Ordinea acțiunilor: „først”, „så” și „etterpå”',
      rule: 'Folosim „først” pentru prima acțiune, „så” pentru următoarea și „etterpå” pentru ceea ce se întâmplă după aceea.',
      examples: ['Først tar du bussen. Så bytter du i sentrum. — Mai întâi iei autobuzul. Apoi schimbi în centru.', 'Etterpå tar du toget. — După aceea iei trenul.'],
      wrong: 'Først du tar bussen.',
    },
    exercises: [
      { type: 'choice', prompt: 'Ce înseamnă „forsinket”?', options: ['Întârziat', 'Disponibil', 'Închis'], answer: 0, explanation: '„Forsinket” descrie ceva care ajunge sau pleacă mai târziu.' },
      { type: 'fill', prompt: 'Completează: „Du må ___ buss i sentrum.”', answer: 'bytte', explanation: 'După „må” folosim verbul fără „å”.' },
      { type: 'order', prompt: 'Construiește „Când pleacă următorul tren?”.', words: ['neste tog', 'går', 'Når'], answer: ['Når', 'går', 'neste tog'], explanation: 'Întrebarea începe cu „Når”, urmat de verb.' },
    ],
  },
  {
    id: 3, title: 'Cumpărături și retururi', duration: 25,
    objectives: ['să ceri o altă mărime', 'să spui dacă un produs este prea mare sau prea mic', 'să întrebi dacă poți schimba un produs'],
    vocabulary: [
      ['En størrelse', 'O mărime', 'Har dere denne i en annen størrelse?', 'Aveți acest produs în altă mărime?', 'størrelse'],
      ['Å prøve', 'A proba / a încerca', 'Kan jeg prøve jakken?', 'Pot proba geaca?', 'prøve'],
      ['For stor', 'Prea mare', 'Denne jakken er for stor.', 'Această geacă este prea mare.'],
      ['For liten', 'Prea mic', 'Genseren er for liten.', 'Puloverul este prea mic.'],
      ['Å bytte', 'A schimba', 'Kan jeg bytte varen?', 'Pot schimba produsul?', 'bytte'],
      ['Å returnere', 'A returna', 'Jeg vil gjerne returnere denne.', 'Aș dori să returnez acest produs.', 'returnere'],
    ],
    dialogue: [
      ['Anna', 'Unnskyld, kan jeg prøve denne jakken?', 'Scuzați-mă, pot proba această geacă?'],
      ['Erik', 'Ja, selvfølgelig. Prøverommet er der borte.', 'Da, desigur. Cabina de probă este acolo.'],
      ['Anna', 'Den er for stor. Har dere en mindre størrelse?', 'Este prea mare. Aveți o mărime mai mică?'],
      ['Erik', 'Ja, jeg skal finne en til deg.', 'Da, voi găsi una pentru dumneavoastră.'],
    ],
    grammar: {
      title: 'Comparații simple: „større”, „mindre” și „billigere”',
      rule: 'Pentru a compara, multe adjective primesc „-ere”. Formele foarte utile la cumpărături sunt „større”, „mindre” și „billigere”.',
      examples: ['Har dere en mindre størrelse? — Aveți o mărime mai mică?', 'Denne jakken er billigere. — Această geacă este mai ieftină.', 'Jeg trenger en større jakke. — Am nevoie de o geacă mai mare.'],
      wrong: 'Jeg trenger en mer liten størrelse.',
    },
    exercises: [
      { type: 'choice', prompt: 'Cum ceri o mărime mai mică?', options: ['En mindre størrelse', 'En litenere størrelse', 'Et mindre størrelsen'], answer: 0, explanation: 'Comparativul lui „liten” este „mindre”.' },
      { type: 'fill', prompt: 'Completează: „Jakken er for ___.”', answer: 'stor', explanation: '„For stor” înseamnă „prea mare”.' },
      { type: 'order', prompt: 'Construiește „Pot schimba produsul?”.', words: ['varen', 'bytte', 'jeg', 'Kan'], answer: ['Kan', 'jeg', 'bytte', 'varen'], explanation: 'Întrebarea începe cu verbul modal „Kan”.' },
    ],
  },
  {
    id: 4, title: 'Locuință și probleme acasă', duration: 26,
    objectives: ['să descrii locuința', 'să anunți o problemă simplă', 'să ceri proprietarului o reparație'],
    vocabulary: [
      ['En leilighet', 'Un apartament', 'Jeg leier en leilighet.', 'Închiriez un apartament.'],
      ['En husleie', 'O chirie', 'Husleien er 9000 kroner.', 'Chiria este de 9000 de coroane.'],
      ['Et depositum', 'O garanție', 'Depositumet er betalt.', 'Garanția este plătită.'],
      ['En utleier', 'Un proprietar', 'Jeg må ringe utleieren.', 'Trebuie să sun proprietarul.'],
      ['Virker ikke', 'Nu funcționează', 'Ovnen virker ikke.', 'Cuptorul nu funcționează.'],
      ['Å reparere', 'A repara', 'Kan du reparere ovnen?', 'Poți repara cuptorul?', 'reparere'],
    ],
    dialogue: [
      ['Nora', 'Hei, ovnen på kjøkkenet virker ikke.', 'Bună, cuptorul din bucătărie nu funcționează.'],
      ['Lars', 'Takk for at du sier fra.', 'Mulțumesc că mă anunți.'],
      ['Nora', 'Kan den bli reparert denne uken?', 'Poate fi reparat săptămâna aceasta?'],
      ['Lars', 'Ja, jeg sender noen i morgen.', 'Da, trimit pe cineva mâine.'],
    ],
    grammar: {
      title: 'Legături simple cu „som”',
      rule: '„Som” înseamnă „care” și leagă o persoană sau un lucru de o informație suplimentară.',
      examples: ['Mannen som bor her, er utleieren. — Bărbatul care locuiește aici este proprietarul.', 'Ovnen som står på kjøkkenet, virker ikke. — Cuptorul care este în bucătărie nu funcționează.'],
      wrong: 'Mannen hvem bor her, er utleieren.',
    },
    exercises: [
      { type: 'choice', prompt: 'Pe cine contactezi pentru o problemă în locuință?', options: ['Utleieren', 'Billetten', 'Holdeplassen'], answer: 0, explanation: '„Utleieren” este proprietarul locuinței închiriate.' },
      { type: 'fill', prompt: 'Completează: „Ovnen ___ står på kjøkkenet, virker ikke.”', answer: 'som', explanation: '„Som” leagă substantivul „ovnen” de informația următoare.' },
      { type: 'order', prompt: 'Construiește „Cuptorul nu funcționează”.', words: ['ikke', 'Ovnen', 'virker'], answer: ['Ovnen', 'virker', 'ikke'], explanation: 'În propoziția simplă, „ikke” apare după verb.' },
    ],
  },
  {
    id: 5, title: 'La medic și la farmacie', duration: 26,
    objectives: ['să ceri o programare', 'să descrii simptome comune', 'să înțelegi o recomandare simplă'],
    vocabulary: [
      ['En time', 'O programare', 'Jeg vil gjerne bestille en time.', 'Aș dori să fac o programare.'],
      ['Feber', 'Febră', 'Jeg har feber.', 'Am febră.'],
      ['Vondt i...', 'Durere în...', 'Jeg har vondt i halsen.', 'Mă doare gâtul.', 'vondt'],
      ['Forkjølet', 'Răcit', 'Jeg er forkjølet.', 'Sunt răcit.'],
      ['En resept', 'O rețetă', 'Du får en resept fra legen.', 'Primești o rețetă de la medic.'],
      ['En medisin', 'Un medicament', 'Du må ta denne medisinen.', 'Trebuie să iei acest medicament.'],
    ],
    dialogue: [
      ['Ana', 'Hei, jeg vil gjerne bestille en time hos legen.', 'Bună, aș dori să fac o programare la medic.'],
      ['Erik', 'Hva gjelder det?', 'Despre ce este vorba?'],
      ['Ana', 'Jeg har feber og vondt i halsen.', 'Am febră și mă doare gâtul.'],
      ['Erik', 'Du kan komme i morgen klokka ni.', 'Puteți veni mâine la ora nouă.'],
    ],
    grammar: {
      title: 'Recomandări cu „bør”',
      rule: '„Bør” înseamnă „ar trebui”. La fel ca după „kan” și „må”, verbul următor apare fără „å”.',
      examples: ['Du bør hvile. — Ar trebui să te odihnești.', 'Du bør ta medisinen. — Ar trebui să iei medicamentul.'],
      wrong: 'Du bør å hvile.',
    },
    exercises: [
      { type: 'choice', prompt: 'Cum spui că te doare gâtul?', options: ['Jeg har vondt i halsen.', 'Jeg er en hals.', 'Jeg tar en time.'], answer: 0, explanation: 'Structura firească este „ha vondt i” + partea corpului.' },
      { type: 'fill', prompt: 'Completează: „Du bør ___.”', answer: 'hvile', explanation: 'După „bør” folosim verbul fără „å”.' },
      { type: 'order', prompt: 'Construiește „Aș dori să fac o programare”.', words: ['en time', 'bestille', 'Jeg', 'vil gjerne'], answer: ['Jeg', 'vil gjerne', 'bestille', 'en time'], explanation: 'Formula politicoasă este „Jeg vil gjerne...”.' },
    ],
  },
];
