export const a2ExtraLessons = [
  {
    id: 6, title: 'Ce ai făcut ieri', duration: 27,
    objectives: ['să povestești activități recente', 'să folosești trecutul verbelor frecvente', 'să înțelegi expresii clare de timp trecut'],
    vocabulary: [
      ['I går', 'Ieri', 'I går jobbet jeg hjemme.', 'Ieri am lucrat acasă.'],
      ['Jobbet', 'Am lucrat', 'Jeg jobbet til klokka fire.', 'Am lucrat până la ora patru.'],
      ['Kjøpte', 'Am cumpărat', 'Jeg kjøpte mat etter jobb.', 'Am cumpărat mâncare după serviciu.'],
      ['Besøkte', 'Am vizitat', 'Vi besøkte familien.', 'Am vizitat familia.'],
      ['Var', 'Am fost / era', 'Jeg var hjemme i går.', 'Am fost acasă ieri.'],
      ['Så', 'Am văzut', 'Vi så en film.', 'Am văzut un film.'],
    ],
    dialogue: [
      ['Anna', 'Hva gjorde du i går?', 'Ce ai făcut ieri?'],
      ['Lars', 'Jeg jobbet til klokka fire. Etterpå kjøpte jeg mat.', 'Am lucrat până la ora patru. După aceea am cumpărat mâncare.'],
      ['Anna', 'Var du hjemme om kvelden?', 'Ai fost acasă seara?'],
      ['Lars', 'Ja, jeg var hjemme og så en film.', 'Da, am fost acasă și am văzut un film.'],
    ],
    grammar: {
      title: 'Preteritul: acțiuni încheiate',
      rule: 'Folosim preteritul pentru o acțiune încheiată într-un moment trecut. Multe verbe primesc „-et” sau „-te”; unele forme frecvente sunt neregulate.',
      examples: ['Jeg jobbet i går. — Am lucrat ieri.', 'Vi kjøpte mat. — Am cumpărat mâncare.', 'Jeg var hjemme. — Am fost acasă.'],
      wrong: 'I går jobber jeg hjemme.',
    },
    exercises: [
      { type: 'choice', prompt: 'Care propoziție vorbește despre ieri?', options: ['Jeg jobber i går.', 'Jeg jobbet i går.', 'Jeg skal jobbe i går.'], answer: 1, explanation: 'Cu „i går” folosim o formă de trecut: „jobbet”.' },
      { type: 'fill', prompt: 'Completează: „Jeg ___ hjemme i går.”', answer: 'var', explanation: 'Forma de trecut a verbului „å være” este „var”.' },
      { type: 'order', prompt: 'Construiește „După aceea am cumpărat mâncare”.', words: ['kjøpte', 'jeg', 'mat', 'Etterpå'], answer: ['Etterpå', 'kjøpte', 'jeg', 'mat'], explanation: 'După „Etterpå”, verbul rămâne pe poziția a doua.' },
    ],
  },
  {
    id: 7, title: 'Experiențe în Norvegia', duration: 28,
    objectives: ['să întrebi despre experiențe', 'să spui unde ai fost', 'să diferențiezi o experiență de un moment trecut precis'],
    vocabulary: [
      ['Har vært', 'Am fost', 'Jeg har vært i Bergen.', 'Am fost în Bergen.'],
      ['Har sett', 'Am văzut', 'Jeg har sett nordlyset.', 'Am văzut aurora boreală.'],
      ['Noen gang', 'Vreodată', 'Har du noen gang vært i Tromsø?', 'Ai fost vreodată în Tromsø?'],
      ['Aldri', 'Niciodată', 'Jeg har aldri vært der.', 'Nu am fost niciodată acolo.'],
      ['Allerede', 'Deja', 'Hun har allerede besøkt Oslo.', 'Ea a vizitat deja Oslo.'],
      ['I fjor', 'Anul trecut', 'Jeg reiste til Bergen i fjor.', 'Am călătorit la Bergen anul trecut.'],
    ],
    dialogue: [
      ['Nora', 'Har du noen gang vært i Nord-Norge?', 'Ai fost vreodată în nordul Norvegiei?'],
      ['Lars', 'Ja, jeg reiste til Tromsø i fjor.', 'Da, am călătorit la Tromsø anul trecut.'],
      ['Nora', 'Har du sett nordlyset?', 'Ai văzut aurora boreală?'],
      ['Lars', 'Ja, jeg har sett det én gang.', 'Da, am văzut-o o dată.'],
    ],
    grammar: {
      title: 'Preterit sau perfect?',
      rule: 'Folosim preteritul cu un moment trecut precis și încheiat. Folosim perfectul „har” + participiu pentru experiențe fără un moment precis sau importante acum.',
      examples: ['Jeg reiste i fjor. — Am călătorit anul trecut.', 'Jeg har vært i Bergen. — Am fost în Bergen.', 'Har du noen gang sett nordlyset? — Ai văzut vreodată aurora boreală?'],
      wrong: 'Jeg har reist til Bergen i fjor.',
    },
    exercises: [
      { type: 'choice', prompt: 'Care variantă este corectă cu „i fjor”?', options: ['Jeg har reist i fjor.', 'Jeg reiste i fjor.', 'Jeg reiser i fjor.'], answer: 1, explanation: '„I fjor” indică un moment trecut încheiat, deci folosim preteritul.' },
      { type: 'fill', prompt: 'Completează: „Jeg ___ vært i Bergen.”', answer: 'har', explanation: 'Perfectul se formează cu „har” + participiu.' },
      { type: 'order', prompt: 'Construiește „Ai fost vreodată în Tromsø?”.', words: ['i Tromsø', 'noen gang', 'vært', 'du', 'Har'], answer: ['Har', 'du', 'noen gang', 'vært', 'i Tromsø'], explanation: 'Întrebarea începe cu „Har”, urmat de subiect.' },
    ],
  },
  {
    id: 8, title: 'Colaborare la serviciu', duration: 28,
    objectives: ['să discuți o sarcină simplă', 'să ceri o explicație', 'să spui de ce ai nevoie de ajutor'],
    vocabulary: [
      ['En oppgave', 'O sarcină', 'Jeg jobber med en oppgave.', 'Lucrez la o sarcină.'],
      ['En frist', 'Un termen-limită', 'Fristen er på fredag.', 'Termenul-limită este vineri.'],
      ['Ferdig', 'Gata / terminat', 'Jeg er snart ferdig.', 'Voi termina în curând.'],
      ['Å forklare', 'A explica', 'Kan du forklare dette en gang til?', 'Poți explica aceasta încă o dată?', 'forklare'],
      ['Å samarbeide', 'A colabora', 'Vi samarbeider om oppgaven.', 'Colaborăm la sarcină.', 'samarbeider'],
      ['Å gi beskjed', 'A anunța', 'Jeg gir beskjed når jeg er ferdig.', 'Te anunț când termin.', 'gir beskjed'],
    ],
    dialogue: [
      ['Nora', 'Hvordan går det med oppgaven?', 'Cum merge sarcina?'],
      ['Mihai', 'Det går bra, men jeg trenger litt hjelp.', 'Merge bine, dar am nevoie de puțin ajutor.'],
      ['Nora', 'Hva skal jeg forklare?', 'Ce să explic?'],
      ['Mihai', 'Kan du vise meg den siste delen?', 'Îmi poți arăta ultima parte?'],
    ],
    grammar: {
      title: 'Explică motivul cu „fordi”',
      rule: '„Fordi” înseamnă „pentru că” și introduce motivul. În propoziția după „fordi”, păstrăm ordinea subiect + verb.',
      examples: ['Jeg spør fordi jeg trenger hjelp. — Întreb pentru că am nevoie de ajutor.', 'Vi samarbeider fordi oppgaven er stor. — Colaborăm pentru că sarcina este mare.'],
      wrong: 'Jeg spør fordi trenger jeg hjelp.',
    },
    exercises: [
      { type: 'choice', prompt: 'Ce este „en frist”?', options: ['O pauză', 'Un termen-limită', 'O întâlnire'], answer: 1, explanation: '„En frist” este data până la care trebuie terminată o sarcină.' },
      { type: 'fill', prompt: 'Completează: „Jeg spør ___ jeg trenger hjelp.”', answer: 'fordi', explanation: '„Fordi” introduce motivul.' },
      { type: 'order', prompt: 'Construiește „Colaborăm la sarcină”.', words: ['om oppgaven', 'samarbeider', 'Vi'], answer: ['Vi', 'samarbeider', 'om oppgaven'], explanation: 'Expresia este „å samarbeide om”.' },
    ],
  },
  {
    id: 9, title: 'Servicii publice și viață digitală', duration: 27,
    objectives: ['să înțelegi pașii unei cereri simple', 'să descrii o problemă de autentificare', 'să ceri ajutor pentru un formular'],
    vocabulary: [
      ['Et skjema', 'Un formular', 'Du må fylle ut dette skjemaet.', 'Trebuie să completezi acest formular.'],
      ['En søknad', 'O cerere', 'Jeg vil sende inn en søknad.', 'Vreau să trimit o cerere.'],
      ['Å logge inn', 'A se autentifica', 'Jeg klarer ikke å logge inn.', 'Nu reușesc să mă autentific.', 'logge inn'],
      ['Et passord', 'O parolă', 'Jeg har glemt passordet mitt.', 'Mi-am uitat parola.'],
      ['En lenke', 'Un link', 'Lenken virker ikke.', 'Linkul nu funcționează.'],
      ['Gyldig', 'Valabil', 'Er legitimasjonen gyldig?', 'Actul de identitate este valabil?'],
    ],
    dialogue: [
      ['Ana', 'Hei, jeg prøver å logge inn, men lenken virker ikke.', 'Bună, încerc să mă autentific, dar linkul nu funcționează.'],
      ['Erik', 'Har du prøvd å lage et nytt passord?', 'Ai încercat să creezi o parolă nouă?'],
      ['Ana', 'Ja, men jeg trenger fortsatt hjelp.', 'Da, dar încă am nevoie de ajutor.'],
      ['Erik', 'Da sender jeg deg en ny lenke.', 'Atunci îți trimit un link nou.'],
    ],
    grammar: {
      title: 'Infinitivul după „prøve”, „ønske” și „klare”',
      rule: 'După „prøve”, „ønske” și „klare” folosim de obicei „å” înaintea verbului următor.',
      examples: ['Jeg prøver å logge inn. — Încerc să mă autentific.', 'Jeg ønsker å sende søknaden. — Doresc să trimit cererea.', 'Jeg klarer ikke å åpne lenken. — Nu reușesc să deschid linkul.'],
      wrong: 'Jeg prøver logge inn.',
    },
    exercises: [
      { type: 'choice', prompt: 'Ce trebuie completat înainte de trimitere?', options: ['Et skjema', 'En holdeplass', 'En jakke'], answer: 0, explanation: '„Et skjema” este un formular.' },
      { type: 'fill', prompt: 'Completează: „Jeg prøver ___ logge inn.”', answer: 'å', explanation: 'După „prøver” păstrăm marca infinitivului „å”.' },
      { type: 'order', prompt: 'Construiește „Mi-am uitat parola”.', words: ['passordet mitt', 'har glemt', 'Jeg'], answer: ['Jeg', 'har glemt', 'passordet mitt'], explanation: 'Perfectul se formează cu „har” + participiu.' },
    ],
  },
  {
    id: 10, title: 'A2 în viața reală', duration: 30,
    objectives: ['să reutilizezi vocabularul întregului nivel A2', 'să alegi corect între prezent, trecut și viitor', 'să gestionezi o conversație cu mai multe situații familiare'],
    vocabulary: [
      ['Har du lyst til...?', 'Ai chef să...?', 'Har du lyst til å reise på lørdag?', 'Ai chef să călătorim sâmbătă?', 'lyst'],
      ['Neste avgang', 'Următoarea plecare', 'Når går neste avgang?', 'Când este următoarea plecare?'],
      ['Kan jeg bytte...?', 'Pot schimba...?', 'Kan jeg bytte denne billetten?', 'Pot schimba acest bilet?', 'bytte'],
      ['Virker ikke', 'Nu funcționează', 'Lenken virker ikke.', 'Linkul nu funcționează.'],
      ['I går', 'Ieri', 'I går jobbet jeg sent.', 'Ieri am lucrat până târziu.'],
      ['Har vært', 'Am fost', 'Jeg har vært i Bergen.', 'Am fost în Bergen.'],
    ],
    dialogue: [
      ['Anna', 'Har du lyst til å reise til Bergen på lørdag?', 'Ai chef să călătorim la Bergen sâmbătă?'],
      ['Lars', 'Ja, gjerne. Jeg har aldri vært der.', 'Da, cu plăcere. Nu am fost niciodată acolo.'],
      ['Anna', 'Jeg skal kjøpe billetter i kveld.', 'Voi cumpăra biletele în seara aceasta.'],
      ['Lars', 'Flott! Gi beskjed hvis lenken ikke virker.', 'Minunat! Anunță-mă dacă linkul nu funcționează.'],
    ],
    grammar: {
      title: 'Recapitulare: prezent, trecut, experiență și plan',
      rule: 'Folosește prezentul pentru ceea ce se întâmplă acum, preteritul pentru un moment trecut precis, perfectul pentru experiențe și „skal” + verb pentru un plan.',
      examples: ['I dag jobber jeg hjemme. — Astăzi lucrez acasă.', 'I går jobbet jeg hjemme. — Ieri am lucrat acasă.', 'Jeg har vært i Bergen. — Am fost în Bergen.', 'Jeg skal reise på lørdag. — Voi călători sâmbătă.'],
      wrong: 'I går har jeg jobbet hjemme klokka tre.',
    },
    exercises: [
      { type: 'choice', prompt: 'Care variantă descrie o experiență fără moment precis?', options: ['Jeg reiste i går.', 'Jeg har vært i Bergen.', 'Jeg skal reise på lørdag.'], answer: 1, explanation: 'Perfectul „har vært” este folosit pentru experiențe.' },
      { type: 'fill', prompt: 'Completează: „I går ___ jeg sent.”', answer: 'jobbet', explanation: '„I går” cere aici forma de trecut „jobbet”.' },
      { type: 'order', prompt: 'Construiește „Voi cumpăra biletele în seara aceasta”.', words: ['i kveld', 'billetter', 'kjøpe', 'Jeg', 'skal'], answer: ['Jeg', 'skal', 'kjøpe', 'billetter', 'i kveld'], explanation: 'Planul se formează cu „skal” + verb fără „å”.' },
    ],
  },
];
