export const b1Lessons = [
  {
    id: 1, title: 'Experiențe și povești', duration: 30,
    objectives: ['să povestești o experiență în ordine cronologică', 'să descrii reacții și sentimente', 'să legi întâmplările într-un text coerent'],
    vocabulary: [
      ['Å oppleve', 'A trăi / a experimenta', 'Jeg opplevde noe uventet på reisen.', 'Am trăit ceva neașteptat în timpul călătoriei.', 'opplevde'],
      ['Å skje', 'A se întâmpla', 'Hva skjedde etter at toget stoppet?', 'Ce s-a întâmplat după ce trenul s-a oprit?', 'skjedde'],
      ['Først', 'Mai întâi', 'Først tok vi bussen til sentrum.', 'Mai întâi am luat autobuzul spre centru.'],
      ['Deretter', 'Apoi', 'Deretter gikk vi videre til fots.', 'Apoi am continuat pe jos.'],
      ['Plutselig', 'Deodată', 'Plutselig begynte det å snø.', 'Deodată a început să ningă.'],
      ['Heldigvis', 'Din fericire', 'Heldigvis fant vi et varmt sted.', 'Din fericire am găsit un loc călduros.'],
      ['Å merke', 'A observa', 'Jeg merket at alle ble stille.', 'Am observat că toți au tăcut.', 'merket'],
      ['Til slutt', 'La final', 'Til slutt kom vi fram til hotellet.', 'La final am ajuns la hotel.'],
    ],
    dialogue: [
      ['Elena', 'Hvordan gikk turen til Lofoten?', 'Cum a fost excursia în Lofoten?'],
      ['Jonas', 'Først gikk alt bra, men plutselig ble fergen innstilt.', 'La început totul a mers bine, dar deodată feribotul a fost anulat.'],
      ['Elena', 'Hva gjorde dere da?', 'Ce ați făcut atunci?'],
      ['Jonas', 'Vi ventet på en buss, og til slutt kom vi fram sent på kvelden.', 'Am așteptat un autobuz și, în cele din urmă, am ajuns târziu seara.'],
    ],
    grammar: { title: 'O poveste coerentă la trecut', rule: 'Folosește preteritul pentru evenimente încheiate și cuvinte precum „først”, „deretter” și „til slutt” pentru a arăta ordinea.', examples: ['Først spiste vi, deretter gikk vi ut. — Mai întâi am mâncat, apoi am ieșit.', 'Plutselig ringte telefonen. — Deodată a sunat telefonul.'], wrong: 'Først vi spiste, deretter vi gikk ut.' },
    exercises: [
      { type: 'choice', prompt: 'Ce cuvânt introduce un eveniment neașteptat?', options: ['Deretter', 'Plutselig', 'Til slutt'], answer: 1, explanation: '„Plutselig” înseamnă „deodată”.' },
      { type: 'fill', prompt: 'Completează: „Hva ___ etter at toget stoppet?”', answer: 'skjedde', explanation: 'Preteritul verbului „å skje” este „skjedde”.' },
      { type: 'order', prompt: 'Construiește „La final am ajuns la hotel”.', words: ['hotellet', 'kom', 'Til slutt', 'vi', 'fram til'], answer: ['Til slutt', 'kom', 'vi', 'fram til', 'hotellet'], explanation: 'Când un adverb ocupă prima poziție, verbul vine înaintea subiectului.' },
    ],
  },
  {
    id: 2, title: 'Opinii și justificări', duration: 31,
    objectives: ['să exprimi clar o opinie', 'să oferi motive și exemple', 'să fii de acord sau să contrazici politicos'],
    vocabulary: [
      ['Etter min mening', 'După părerea mea', 'Etter min mening er kollektivtransport viktig.', 'După părerea mea, transportul public este important.'],
      ['Å være enig', 'A fi de acord', 'Jeg er enig med deg i dette.', 'Sunt de acord cu tine în această privință.', 'enig'],
      ['Å være uenig', 'A nu fi de acord', 'Jeg er delvis uenig i forslaget.', 'Nu sunt întru totul de acord cu propunerea.', 'uenig'],
      ['En fordel', 'Un avantaj', 'En fordel er at vi sparer tid.', 'Un avantaj este că economisim timp.'],
      ['En ulempe', 'Un dezavantaj', 'Ulempen er at det koster mer.', 'Dezavantajul este că este mai scump.', 'Ulempen'],
      ['Fordi', 'Deoarece', 'Jeg sykler fordi det er miljøvennlig.', 'Merg cu bicicleta deoarece este ecologic.'],
      ['Derfor', 'De aceea', 'Bussen var forsinket, derfor kom jeg sent.', 'Autobuzul a întârziat, de aceea am ajuns târziu.'],
      ['Selv om', 'Chiar dacă', 'Selv om det regnet, gikk vi på tur.', 'Chiar dacă a plouat, am mers în drumeție.'],
    ],
    dialogue: [
      ['Mina', 'Synes du at flere bør jobbe hjemmefra?', 'Crezi că mai mulți oameni ar trebui să lucreze de acasă?'],
      ['Oskar', 'Ja, fordi mange sparer tid på reisen.', 'Da, deoarece mulți economisesc timpul de navetă.'],
      ['Mina', 'Det er jeg enig i, men samarbeid kan bli vanskeligere.', 'Sunt de acord, dar colaborarea poate deveni mai dificilă.'],
      ['Oskar', 'Det er sant. Derfor bør ansatte kunne velge.', 'Este adevărat. De aceea angajații ar trebui să poată alege.'],
    ],
    grammar: { title: 'Cauză, rezultat și contrast', rule: '„Fordi” introduce cauza, „derfor” rezultatul, iar „selv om” un contrast. După „derfor” urmează verbul, apoi subiectul.', examples: ['Jeg blir hjemme fordi jeg er syk. — Rămân acasă pentru că sunt bolnav.', 'Jeg er syk, derfor blir jeg hjemme. — Sunt bolnav, de aceea rămân acasă.'], wrong: 'Jeg er syk, derfor jeg blir hjemme.' },
    exercises: [
      { type: 'choice', prompt: 'Cum introduci politicos o părere personală?', options: ['Til slutt', 'Etter min mening', 'Heldigvis'], answer: 1, explanation: '„Etter min mening” înseamnă „după părerea mea”.' },
      { type: 'fill', prompt: 'Completează: „Det regnet, ___ ble vi hjemme.”', answer: 'derfor', explanation: '„Derfor” introduce rezultatul.' },
      { type: 'order', prompt: 'Construiește „Chiar dacă ploua, am ieșit”.', words: ['gikk', 'det regnet', 'vi ut', 'Selv om'], answer: ['Selv om', 'det regnet', 'gikk', 'vi ut'], explanation: 'După propoziția subordonată, propoziția principală începe cu verbul.' },
    ],
  },
  {
    id: 3, title: 'Responsabilități la serviciu', duration: 32,
    objectives: ['să descrii responsabilități profesionale', 'să clarifici sarcini și termene', 'să oferi și să primești feedback'],
    vocabulary: [
      ['Et ansvar', 'O responsabilitate', 'Jeg har ansvar for kundekontakt.', 'Sunt responsabil de contactul cu clienții.'],
      ['En arbeidsoppgave', 'O sarcină de lucru', 'Denne arbeidsoppgaven må være ferdig i morgen.', 'Această sarcină trebuie terminată mâine.'],
      ['En frist', 'Un termen-limită', 'Kan vi flytte fristen til mandag?', 'Putem muta termenul-limită până luni?'],
      ['Et samarbeid', 'O colaborare', 'Godt samarbeid gjør arbeidet lettere.', 'O colaborare bună face munca mai ușoară.'],
      ['Å foreslå', 'A propune', 'Jeg foreslår at vi møtes tidligere.', 'Propun să ne întâlnim mai devreme.', 'foreslår'],
      ['Å avklare', 'A clarifica', 'Vi må avklare hvem som gjør hva.', 'Trebuie să clarificăm cine și ce face.'],
      ['En tilbakemelding', 'Un feedback', 'Takk for en konkret tilbakemelding.', 'Mulțumesc pentru feedbackul concret.'],
      ['Å fordele', 'A distribui', 'Lederen fordelte oppgavene mellom oss.', 'Managerul a distribuit sarcinile între noi.', 'fordelte'],
    ],
    dialogue: [
      ['Leder', 'Kan vi avklare hvem som har ansvar for rapporten?', 'Putem clarifica cine este responsabil de raport?'],
      ['Irina', 'Jeg kan skrive første del hvis Martin sjekker tallene.', 'Pot scrie prima parte dacă Martin verifică cifrele.'],
      ['Martin', 'Det passer. Når er fristen?', 'Este în regulă. Când este termenul-limită?'],
      ['Leder', 'Rapporten må leveres innen torsdag ettermiddag.', 'Raportul trebuie predat până joi după-amiază.'],
    ],
    grammar: { title: 'Pasivul în comunicarea profesională', rule: 'Pasivul se formează frecvent cu „bli” + participiu sau cu terminația „-s” când acțiunea este mai importantă decât persoana care o face.', examples: ['Rapporten blir sendt i dag. — Raportul este trimis astăzi.', 'Søknaden må leveres innen fredag. — Cererea trebuie depusă până vineri.'], wrong: 'Rapporten blir sende i dag.' },
    exercises: [
      { type: 'choice', prompt: 'Ce înseamnă „å avklare”?', options: ['A amâna', 'A clarifica', 'A angaja'], answer: 1, explanation: '„Å avklare” înseamnă a face un lucru clar.' },
      { type: 'fill', prompt: 'Completează: „Rapporten blir ___ i dag.”', answer: 'sendt', explanation: 'După „blir” folosim participiul „sendt”.' },
      { type: 'order', prompt: 'Construiește „Cererea trebuie depusă până vineri”.', words: ['innen fredag', 'leveres', 'Søknaden', 'må'], answer: ['Søknaden', 'må', 'leveres', 'innen fredag'], explanation: 'Forma pasivă „leveres” urmează după verbul modal.' },
    ],
  },
  {
    id: 4, title: 'Căutarea unui loc de muncă', duration: 34,
    objectives: ['să înțelegi un anunț de angajare', 'să vorbești despre experiența ta', 'să răspunzi la întrebări de interviu'],
    vocabulary: [
      ['En stillingsannonse', 'Un anunț de angajare', 'Jeg fant stillingsannonsen på nettet.', 'Am găsit anunțul de angajare online.'],
      ['En søknad', 'O cerere / candidatură', 'Søknaden bør være kort og konkret.', 'Candidatura ar trebui să fie scurtă și concretă.'],
      ['En CV', 'Un CV', 'Jeg har oppdatert CV-en min.', 'Mi-am actualizat CV-ul.'],
      ['En kvalifikasjon', 'O calificare', 'Hvilke kvalifikasjoner krever stillingen?', 'Ce calificări cere postul?', 'kvalifikasjoner'],
      ['Arbeidserfaring', 'Experiență profesională', 'Jeg har fem års arbeidserfaring.', 'Am cinci ani de experiență profesională.'],
      ['Et intervju', 'Un interviu', 'Hun ble invitert til intervju.', 'Ea a fost invitată la interviu.'],
      ['Å ansette', 'A angaja', 'Bedriften ønsker å ansette to personer.', 'Compania dorește să angajeze două persoane.'],
      ['En referanse', 'O recomandare profesională', 'Kan jeg oppgi deg som referanse?', 'Pot să te menționez ca persoană de referință?'],
    ],
    dialogue: [
      ['Intervjuer', 'Kan du fortelle litt om arbeidserfaringen din?', 'Ne poți povesti puțin despre experiența ta profesională?'],
      ['Søker', 'Jeg har jobbet med kundeservice i fem år.', 'Am lucrat în relații cu clienții timp de cinci ani.'],
      ['Intervjuer', 'Hvorfor ønsker du denne stillingen?', 'De ce îți dorești acest post?'],
      ['Søker', 'Fordi jeg vil bruke erfaringen min og lære noe nytt.', 'Pentru că vreau să-mi folosesc experiența și să învăț ceva nou.'],
    ],
    grammar: { title: 'Răspunsuri politicoase și ipotetice', rule: '„Jeg kunne” și „jeg ville” exprimă posibilități sau dorințe într-un ton politicos. În interviu, oferă apoi un motiv concret.', examples: ['Jeg kunne begynne neste måned. — Aș putea începe luna viitoare.', 'Jeg ville gjerne utvikle meg videre. — Mi-ar plăcea să mă dezvolt în continuare.'], wrong: 'Jeg kunne å begynne neste måned.' },
    exercises: [
      { type: 'choice', prompt: 'Ce document rezumă experiența și studiile?', options: ['En frist', 'En CV', 'En referanse'], answer: 1, explanation: 'CV-ul prezintă experiența, studiile și competențele.' },
      { type: 'fill', prompt: 'Completează: „Jeg ___ begynne neste måned.”', answer: 'kunne', explanation: '„Kunne” exprimă aici o posibilitate politicoasă.' },
      { type: 'order', prompt: 'Construiește „Am cinci ani de experiență profesională”.', words: ['arbeidserfaring', 'fem års', 'har', 'Jeg'], answer: ['Jeg', 'har', 'fem års', 'arbeidserfaring'], explanation: 'Cantitatea apare înaintea substantivului.' },
    ],
  },
  {
    id: 5, title: 'Sănătate și comunicarea cu medicul', duration: 33,
    objectives: ['să descrii precis simptomele', 'să înțelegi recomandările medicului', 'să ceri explicații suplimentare'],
    vocabulary: [
      ['Et symptom', 'Un simptom', 'Symptomene begynte for tre dager siden.', 'Simptomele au început acum trei zile.', 'Symptomene'],
      ['En undersøkelse', 'O consultație / examinare', 'Legen vil gjøre en grundig undersøkelse.', 'Medicul va face o examinare amănunțită.'],
      ['En behandling', 'Un tratament', 'Behandlingen varer i to uker.', 'Tratamentul durează două săptămâni.'],
      ['En henvisning', 'O trimitere medicală', 'Du får en henvisning til en spesialist.', 'Primești o trimitere la un specialist.'],
      ['En bivirkning', 'Un efect secundar', 'Medisinen kan gi milde bivirkninger.', 'Medicamentul poate avea efecte secundare ușoare.', 'bivirkninger'],
      ['Å anbefale', 'A recomanda', 'Legen anbefalte at jeg hvilte mer.', 'Medicul mi-a recomandat să mă odihnesc mai mult.', 'anbefalte'],
      ['Å beskrive', 'A descrie', 'Kan du beskrive smerten nærmere?', 'Poți descrie durerea mai exact?'],
      ['Bekymret', 'Îngrijorat', 'Jeg er bekymret fordi smerten ikke går over.', 'Sunt îngrijorat deoarece durerea nu trece.'],
    ],
    dialogue: [
      ['Lege', 'Kan du beskrive når smerten begynte?', 'Poți descrie când a început durerea?'],
      ['Pasient', 'Den begynte for tre dager siden og blir verre om kvelden.', 'A început acum trei zile și se agravează seara.'],
      ['Lege', 'Jeg vil undersøke deg og ta noen prøver.', 'Vreau să te consult și să fac câteva analize.'],
      ['Pasient', 'Kan du forklare hva prøvene skal vise?', 'Îmi poți explica ce ar trebui să arate analizele?'],
    ],
    grammar: { title: 'Vorbirea indirectă după recomandări', rule: 'După un verb la trecut precum „anbefalte” sau „sa”, propoziția relatată apare adesea tot la trecut.', examples: ['Legen sa at jeg måtte hvile. — Medicul a spus că trebuia să mă odihnesc.', 'Hun anbefalte at jeg drakk mer vann. — Ea mi-a recomandat să beau mai multă apă.'], wrong: 'Legen sa at måtte jeg hvile.' },
    exercises: [
      { type: 'choice', prompt: 'Ce este „en henvisning”?', options: ['O rețetă', 'O trimitere medicală', 'Un efect secundar'], answer: 1, explanation: 'O „henvisning” permite consultarea unui specialist.' },
      { type: 'fill', prompt: 'Completează: „Legen sa at jeg ___ hvile.”', answer: 'måtte', explanation: 'În relatarea la trecut, „må” devine „måtte”.' },
      { type: 'order', prompt: 'Construiește „Poți descrie durerea mai exact?”', words: ['smerten', 'Kan', 'nærmere', 'du beskrive'], answer: ['Kan', 'du beskrive', 'smerten', 'nærmere'], explanation: 'Întrebarea da/nu începe cu verbul modal.' },
    ],
  },
  {
    id: 6, title: 'Locuință, contract și reclamații', duration: 34,
    objectives: ['să înțelegi termenii esențiali ai unui contract', 'să anunți o problemă în scris', 'să formulezi o reclamație politicoasă'],
    vocabulary: [
      ['En leiekontrakt', 'Un contract de închiriere', 'Jeg har lest hele leiekontrakten.', 'Am citit întregul contract de închiriere.'],
      ['Et depositum', 'O garanție', 'Depositumet skal stå på en egen konto.', 'Garanția trebuie păstrată într-un cont separat.'],
      ['En utleier', 'Un proprietar care închiriază', 'Utleieren må få beskjed om skaden.', 'Proprietarul trebuie anunțat despre daună.'],
      ['Vedlikehold', 'Întreținere', 'Utleieren har ansvar for nødvendig vedlikehold.', 'Proprietarul este responsabil de întreținerea necesară.'],
      ['En skade', 'O daună', 'Det har oppstått en skade på badet.', 'A apărut o daună în baie.'],
      ['Å melde fra', 'A anunța', 'Jeg meldte fra så snart jeg oppdaget problemet.', 'Am anunțat imediat ce am descoperit problema.', 'meldte fra'],
      ['En oppsigelse', 'O reziliere / notificare', 'Oppsigelsen må sendes skriftlig.', 'Notificarea de reziliere trebuie trimisă în scris.'],
      ['Skriftlig', 'În scris', 'Kan du bekrefte avtalen skriftlig?', 'Poți confirma înțelegerea în scris?'],
    ],
    dialogue: [
      ['Leietaker', 'Hei, jeg vil melde fra om en vannskade på badet.', 'Bună, vreau să anunț o daună provocată de apă în baie.'],
      ['Utleier', 'Når oppdaget du problemet?', 'Când ai descoperit problema?'],
      ['Leietaker', 'I går kveld. Jeg har sendt bilder på e-post.', 'Ieri seară. Am trimis fotografii prin e-mail.'],
      ['Utleier', 'Takk. Skaden skal undersøkes i morgen.', 'Mulțumesc. Dauna va fi verificată mâine.'],
    ],
    grammar: { title: 'Cereri formale și pasiv', rule: 'Într-un mesaj formal, formule precum „Jeg ber om at...” și pasivul păstrează tonul clar și neutru.', examples: ['Jeg ber om at skaden blir reparert. — Solicit ca dauna să fie reparată.', 'Avtalen må bekreftes skriftlig. — Înțelegerea trebuie confirmată în scris.'], wrong: 'Jeg ber at reparere skaden.' },
    exercises: [
      { type: 'choice', prompt: 'Cum trebuie trimisă notificarea de reziliere?', options: ['Muntlig', 'Skriftlig', 'Tilfeldig'], answer: 1, explanation: '„Skriftlig” înseamnă „în scris”.' },
      { type: 'fill', prompt: 'Completează: „Avtalen må ___ skriftlig.”', answer: 'bekreftes', explanation: '„Bekreftes” este forma pasivă: a fi confirmată.' },
      { type: 'order', prompt: 'Construiește „Am anunțat despre daună”.', words: ['skaden', 'fra om', 'Jeg meldte'], answer: ['Jeg meldte', 'fra om', 'skaden'], explanation: 'Expresia este „å melde fra om noe”.' },
    ],
  },
  {
    id: 7, title: 'Știri și societate', duration: 35,
    objectives: ['să înțelegi ideea principală a unei știri', 'să distingi faptele de opinii', 'să rezumi informații dintr-o sursă'],
    vocabulary: [
      ['En kilde', 'O sursă', 'Artikkelen viser til flere kilder.', 'Articolul face referire la mai multe surse.'],
      ['En overskrift', 'Un titlu de presă', 'Overskriften fanget oppmerksomheten min.', 'Titlul mi-a atras atenția.'],
      ['Pålitelig', 'De încredere', 'Er denne nettsiden en pålitelig kilde?', 'Este acest site o sursă de încredere?'],
      ['Å hevde', 'A susține / a afirma', 'Forfatteren hevder at tiltaket virker.', 'Autorul susține că măsura funcționează.', 'hevder'],
      ['Ifølge', 'Potrivit / conform', 'Ifølge avisen har prisene gått ned.', 'Potrivit ziarului, prețurile au scăzut.'],
      ['En hendelse', 'Un eveniment', 'Nyheten beskriver en hendelse i Oslo.', 'Știrea descrie un eveniment din Oslo.'],
      ['Et samfunn', 'O societate', 'Tilliten er viktig i et samfunn.', 'Încrederea este importantă într-o societate.'],
      ['Å påvirke', 'A influența', 'Sosiale medier påvirker hvordan vi leser nyheter.', 'Rețelele sociale influențează modul în care citim știrile.', 'påvirker'],
    ],
    dialogue: [
      ['Ada', 'Har du lest saken om kollektivtransport?', 'Ai citit știrea despre transportul public?'],
      ['Emil', 'Ja, men jeg vet ikke om kilden er pålitelig.', 'Da, dar nu știu dacă sursa este de încredere.'],
      ['Ada', 'Ifølge kommunen skal tilbudet bli bedre neste år.', 'Potrivit primăriei, serviciul se va îmbunătăți anul viitor.'],
      ['Emil', 'Da bør vi sjekke hva kommunen faktisk har publisert.', 'Atunci ar trebui să verificăm ce a publicat efectiv primăria.'],
    ],
    grammar: { title: 'Relatarea unei informații', rule: 'Folosește „ifølge” + sursă sau „X sier/hever at...” pentru a arăta clar de unde vine informația.', examples: ['Ifølge avisen øker prisene. — Potrivit ziarului, prețurile cresc.', 'Kommunen sier at tilbudet skal bli bedre. — Primăria spune că serviciul se va îmbunătăți.'], wrong: 'Ifølge sier avisen at prisene øker.' },
    exercises: [
      { type: 'choice', prompt: 'Ce cuvânt indică sursa unei informații?', options: ['Plutselig', 'Ifølge', 'Derfor'], answer: 1, explanation: '„Ifølge” înseamnă „potrivit/conform”.' },
      { type: 'fill', prompt: 'Completează: „___ avisen har prisene gått ned.”', answer: 'Ifølge', explanation: '„Ifølge” este urmat direct de sursă.' },
      { type: 'order', prompt: 'Construiește „Primăria spune că serviciul se îmbunătățește”.', words: ['blir bedre', 'Kommunen', 'at tilbudet', 'sier'], answer: ['Kommunen', 'sier', 'at tilbudet', 'blir bedre'], explanation: '„At” introduce informația relatată.' },
    ],
  },
  {
    id: 8, title: 'Cultură, relații și integrare', duration: 33,
    objectives: ['să discuți despre obiceiuri și diferențe culturale', 'să explici o neînțelegere', 'să vorbești despre apartenență și integrare'],
    vocabulary: [
      ['En tilhørighet', 'Un sentiment de apartenență', 'Språket gir meg sterkere tilhørighet.', 'Limba îmi oferă un sentiment mai puternic de apartenență.'],
      ['Et fellesskap', 'O comunitate', 'Dugnaden skaper et godt fellesskap.', 'Munca voluntară creează o comunitate unită.'],
      ['En vane', 'Un obicei', 'Det tok tid å forstå lokale vaner.', 'A fost nevoie de timp pentru a înțelege obiceiurile locale.', 'vaner'],
      ['Høflig', 'Politicos', 'Hva regnes som høflig i Norge?', 'Ce este considerat politicos în Norvegia?'],
      ['Å tilpasse seg', 'A se adapta', 'Hun tilpasset seg raskt til den nye jobben.', 'Ea s-a adaptat repede la noul loc de muncă.', 'tilpasset seg'],
      ['En misforståelse', 'O neînțelegere', 'Det hele var en liten misforståelse.', 'Totul a fost o mică neînțelegere.'],
      ['En dugnad', 'O activitate voluntară comună', 'Naboene møtes til dugnad hver vår.', 'Vecinii se întâlnesc pentru muncă voluntară în fiecare primăvară.'],
      ['Inkludert', 'Inclus', 'Jeg følte meg inkludert fra første dag.', 'M-am simțit inclus din prima zi.'],
    ],
    dialogue: [
      ['Radu', 'Hva betyr det at borettslaget har dugnad?', 'Ce înseamnă că asociația de locatari organizează o activitate voluntară?'],
      ['Ingrid', 'Vi møtes og gjør praktiske oppgaver sammen.', 'Ne întâlnim și facem împreună diverse activități practice.'],
      ['Radu', 'Må alle delta?', 'Trebuie să participe toată lumea?'],
      ['Ingrid', 'Det er vanlig å bidra, og det er en fin måte å bli kjent på.', 'Este obișnuit să contribui și este o modalitate bună de a cunoaște oamenii.'],
    ],
    grammar: { title: 'Verbele reflexive și reciprocitatea', rule: 'Pronumele reflexiv se acordă cu subiectul: „jeg tilpasser meg”, „vi tilpasser oss”. Expresia „bli kjent med” înseamnă a cunoaște treptat pe cineva.', examples: ['Vi tilpasser oss nye vaner. — Ne adaptăm la obiceiuri noi.', 'De ble kjent med naboene. — Ei i-au cunoscut pe vecini.'], wrong: 'Vi tilpasser seg nye vaner.' },
    exercises: [
      { type: 'choice', prompt: 'Ce este o „dugnad”?', options: ['O sărbătoare națională', 'O activitate voluntară comună', 'O ședință obligatorie'], answer: 1, explanation: '„Dugnad” este munca făcută voluntar împreună pentru comunitate.' },
      { type: 'fill', prompt: 'Completează: „Vi tilpasser ___ nye vaner.”', answer: 'oss', explanation: 'Pentru subiectul „vi”, pronumele reflexiv este „oss”.' },
      { type: 'order', prompt: 'Construiește „M-am simțit inclus din prima zi”.', words: ['første dag', 'inkludert', 'Jeg følte meg', 'fra'], answer: ['Jeg følte meg', 'inkludert', 'fra', 'første dag'], explanation: 'Expresia reflexivă este „å føle seg”.' },
    ],
  },
  {
    id: 9, title: 'Servicii publice și comunicare formală', duration: 35,
    objectives: ['să completezi și să urmărești o cerere', 'să scrii un mesaj formal clar', 'să ceri informații prin întrebări indirecte'],
    vocabulary: [
      ['Et vedlegg', 'Un document anexat', 'Husk å legge ved alle vedleggene.', 'Nu uita să anexezi toate documentele.', 'vedleggene'],
      ['En saksbehandling', 'O procesare administrativă', 'Saksbehandlingen kan ta fire uker.', 'Procesarea administrativă poate dura patru săptămâni.'],
      ['En frist', 'Un termen-limită', 'Fristen for å søke er 1. september.', 'Termenul-limită pentru depunere este 1 septembrie.'],
      ['En innlogging', 'O autentificare', 'Jeg har problemer med innloggingen.', 'Am probleme cu autentificarea.'],
      ['Å fylle ut', 'A completa', 'Skjemaet må fylles ut digitalt.', 'Formularul trebuie completat digital.', 'fylles ut'],
      ['Å dokumentere', 'A dovedi cu documente', 'Du må dokumentere inntekten din.', 'Trebuie să îți dovedești venitul cu documente.'],
      ['En bekreftelse', 'O confirmare', 'Du får en bekreftelse på e-post.', 'Primești o confirmare prin e-mail.'],
      ['Å behandle', 'A procesa / a soluționa', 'Kontoret behandler søknaden din.', 'Biroul procesează cererea ta.', 'behandler'],
    ],
    dialogue: [
      ['Bruker', 'Hei, jeg lurer på om søknaden min er mottatt.', 'Bună, aș dori să știu dacă cererea mea a fost primită.'],
      ['Veileder', 'Har du fått en bekreftelse på e-post?', 'Ai primit o confirmare prin e-mail?'],
      ['Bruker', 'Ja, men kan du si hvor lang saksbehandlingstiden er?', 'Da, dar îmi poți spune cât durează procesarea?'],
      ['Veileder', 'For tiden tar den omtrent fire uker.', 'În prezent durează aproximativ patru săptămâni.'],
    ],
    grammar: { title: 'Întrebări indirecte', rule: 'După „Jeg lurer på...” sau „Kan du si...”, întrebarea are ordinea unei propoziții afirmative: cuvânt interogativ + subiect + verb.', examples: ['Kan du si når kontoret åpner? — Îmi poți spune când se deschide biroul?', 'Jeg lurer på om søknaden er mottatt. — Aș dori să știu dacă cererea a fost primită.'], wrong: 'Kan du si når åpner kontoret?' },
    exercises: [
      { type: 'choice', prompt: 'Ce primești după înregistrarea unei cereri?', options: ['En bekreftelse', 'En vane', 'En overskrift'], answer: 0, explanation: 'O confirmare arată că cererea a fost înregistrată.' },
      { type: 'fill', prompt: 'Completează: „Jeg lurer på ___ søknaden er mottatt.”', answer: 'om', explanation: '„Om” introduce o întrebare indirectă de tip da/nu.' },
      { type: 'order', prompt: 'Construiește „Îmi poți spune când se deschide biroul?”', words: ['kontoret', 'når', 'Kan du si', 'åpner'], answer: ['Kan du si', 'når', 'kontoret', 'åpner'], explanation: 'În întrebarea indirectă, subiectul precedă verbul.' },
    ],
  },
  {
    id: 10, title: 'Prezentare, argumentare și planuri', duration: 38,
    objectives: ['să susții o prezentare scurtă și coerentă', 'să explici un obiectiv și pașii necesari', 'să rezumi și să formulezi o concluzie'],
    vocabulary: [
      ['En innledning', 'O introducere', 'Innledningen forklarer temaet kort.', 'Introducerea explică pe scurt tema.'],
      ['Et hovedpoeng', 'O idee principală', 'Mitt hovedpoeng er at språk krever øvelse.', 'Ideea mea principală este că limba cere exercițiu.'],
      ['Et eksempel', 'Un exemplu', 'La meg gi et konkret eksempel.', 'Permite-mi să dau un exemplu concret.'],
      ['En konklusjon', 'O concluzie', 'Konklusjonen følger av argumentene.', 'Concluzia rezultă din argumente.'],
      ['Et mål', 'Un obiectiv', 'Målet mitt er å bruke norsk på jobb.', 'Obiectivul meu este să folosesc norvegiana la serviciu.'],
      ['Å oppsummere', 'A rezuma', 'Til slutt vil jeg oppsummere hovedpunktene.', 'La final vreau să rezum ideile principale.'],
      ['Å begrunne', 'A justifica', 'Du bør begrunne valget med et eksempel.', 'Ar trebui să justifici alegerea printr-un exemplu.'],
      ['Framover', 'Pe viitor', 'Framover skal jeg øve litt hver dag.', 'Pe viitor voi exersa puțin în fiecare zi.'],
    ],
    dialogue: [
      ['Veileder', 'Hva er målet med presentasjonen din?', 'Care este obiectivul prezentării tale?'],
      ['Student', 'Jeg vil forklare hvordan man kan lære norsk i hverdagen.', 'Vreau să explic cum se poate învăța norvegiana în viața de zi cu zi.'],
      ['Veileder', 'Husk å begrunne rådene med eksempler.', 'Nu uita să justifici sfaturile prin exemple.'],
      ['Student', 'Ja, og til slutt skal jeg oppsummere hovedpoengene.', 'Da, iar la final voi rezuma ideile principale.'],
    ],
    grammar: { title: 'Structura unei prezentări', rule: 'Leagă ideile cu expresii de orientare: „først vil jeg...”, „for eksempel...”, „på den andre siden...” și „til slutt...”.', examples: ['Først vil jeg presentere temaet. — Mai întâi voi prezenta tema.', 'Til slutt vil jeg trekke en konklusjon. — La final voi formula o concluzie.'], wrong: 'Først jeg vil presentere temaet.' },
    exercises: [
      { type: 'choice', prompt: 'Ce parte prezintă pe scurt tema?', options: ['En innledning', 'Et vedlegg', 'En bivirkning'], answer: 0, explanation: 'Introducerea orientează publicul către temă.' },
      { type: 'fill', prompt: 'Completează: „Til slutt vil jeg ___ hovedpunktene.”', answer: 'oppsummere', explanation: 'După „vil” folosim infinitivul fără „å”.' },
      { type: 'order', prompt: 'Construiește „Mai întâi voi prezenta tema”.', words: ['temaet', 'vil', 'Først', 'jeg', 'presentere'], answer: ['Først', 'vil', 'jeg', 'presentere', 'temaet'], explanation: 'După „først” pe prima poziție, verbul precedă subiectul.' },
    ],
  },
];
