export const b2Lessons = [
  {
    id: 1, title: 'Opinii și argumentare', duration: 32,
    objectives: ['să formulezi o opinie nuanțată', 'să compari argumente opuse', 'să răspunzi politicos unei obiecții'],
    vocabulary: [
      ['Etter min mening', 'După părerea mea', 'Etter min mening bør kollektivtransport være billigere.', 'După părerea mea, transportul public ar trebui să fie mai ieftin.'],
      ['På den ene siden', 'Pe de o parte', 'På den ene siden sparer vi tid, men på den andre siden øker kostnadene.', 'Pe de o parte economisim timp, dar pe de altă parte cresc costurile.'],
      ['Likevel', 'Totuși', 'Forslaget er dyrt, men likevel nødvendig.', 'Propunerea este costisitoare, dar totuși necesară.'],
      ['Avgjørende', 'Hotărâtor / esențial', 'Tillit er avgjørende for et godt samarbeid.', 'Încrederea este esențială pentru o colaborare bună.'],
      ['Å påstå', 'A susține', 'Rapporten påstår at tiltaket har virket.', 'Raportul susține că măsura a funcționat.', 'påstår'],
      ['Nyansert', 'Nuanțat', 'Debatten krever et mer nyansert perspektiv.', 'Dezbaterea necesită o perspectivă mai nuanțată.'],
    ],
    dialogue: [
      ['Ingrid', 'Jeg mener at hjemmekontor gir større fleksibilitet.', 'Consider că munca de acasă oferă mai multă flexibilitate.'],
      ['Jonas', 'Det er jeg delvis enig i, men samarbeid kan bli vanskeligere.', 'Sunt parțial de acord, dar colaborarea poate deveni mai dificilă.'],
      ['Ingrid', 'Det er et godt poeng. Likevel avhenger mye av hvordan arbeidet organiseres.', 'Este un argument bun. Totuși, multe depind de felul în care este organizată munca.'],
      ['Jonas', 'Da, en kombinasjon kan være den mest hensiktsmessige løsningen.', 'Da, o combinație poate fi soluția cea mai potrivită.'],
    ],
    grammar: { title: 'Ordinea cuvintelor după conectori', rule: 'Conectorii ocupă adesea primul loc, iar verbul conjugat rămâne pe poziția a doua în propoziția principală.', examples: ['Likevel fortsatte de arbeidet. — Totuși, au continuat munca.', 'Derfor må vi vurdere alternativene. — De aceea trebuie să evaluăm alternativele.'], wrong: 'Likevel de fortsatte arbeidet.' },
    exercises: [
      { type: 'choice', prompt: 'Ce expresie introduce două perspective opuse?', options: ['Etter hvert','På den ene siden','I tillegg'], answer: 1, explanation: 'Expresia este asociată de regulă cu „på den andre siden”.' },
      { type: 'fill', prompt: 'Completează: „Forslaget er kostbart, men ___ nødvendig.”', answer: 'likevel', explanation: '„Likevel” introduce contrastul față de prima idee.' },
      { type: 'order', prompt: 'Construiește „De aceea trebuie să evaluăm alternativele.”', words: ['alternativene', 'Derfor', 'vurdere', 'vi', 'må'], answer: ['Derfor', 'må', 'vi', 'vurdere', 'alternativene'], explanation: 'După „Derfor”, verbul conjugat ocupă poziția a doua.' },
    ],
  },
  {
    id: 2, title: 'Comunicare profesională', duration: 34,
    objectives: ['să discuți responsabilități și termene', 'să oferi feedback constructiv', 'să negociezi o soluție la serviciu'],
    vocabulary: [
      ['Et ansvar', 'O responsabilitate', 'Hun har ansvar for den faglige kvaliteten.', 'Ea este responsabilă pentru calitatea profesională.'],
      ['Kompetanse', 'Competență', 'Stillingen krever både teknisk og sosial kompetanse.', 'Postul necesită atât competență tehnică, cât și socială.'],
      ['En frist', 'Un termen-limită', 'Vi må overholde fristen på fredag.', 'Trebuie să respectăm termenul-limită de vineri.'],
      ['Tilbakemelding', 'Feedback', 'Takk for en konkret og nyttig tilbakemelding.', 'Mulțumesc pentru un feedback concret și util.'],
      ['Å gjennomføre', 'A realiza / implementa', 'Teamet gjennomførte prosjektet som planlagt.', 'Echipa a realizat proiectul conform planului.', 'gjennomførte'],
      ['Å forhandle', 'A negocia', 'Partene forhandler om en ny avtale.', 'Părțile negociază un nou acord.', 'forhandler'],
    ],
    dialogue: [
      ['Leder', 'Hvordan ligger vi an i forhold til fristen?', 'Cum stăm în raport cu termenul-limită?'],
      ['Rådgiver', 'Vi er i rute, men trenger en avklaring om budsjettet.', 'Suntem în grafic, dar avem nevoie de o clarificare privind bugetul.'],
      ['Leder', 'Kan du sende meg en oppdatert oversikt innen klokka tre?', 'Îmi poți trimite o situație actualizată până la ora trei?'],
      ['Rådgiver', 'Ja, og jeg foreslår at vi går gjennom den sammen.', 'Da, și propun să o analizăm împreună.'],
    ],
    grammar: { title: 'Pasivul cu „bli” și „-s”', rule: 'Pasivul cu „bli” accentuează procesul, iar forma în „-s” este frecventă în texte formale și instrucțiuni.', examples: ['Rapporten blir vurdert i morgen. — Raportul va fi evaluat mâine.', 'Søknaden behandles fortløpende. — Cererea este procesată continuu.'], wrong: 'Rapporten vurderer i morgen.' },
    exercises: [
      { type: 'choice', prompt: 'Care variantă este pasivă?', options: ['Vi vurderer rapporten.','Rapporten blir vurdert.','Rapporten vurderer oss.'], answer: 1, explanation: '„Blir vurdert” este construcția pasivă.' },
      { type: 'fill', prompt: 'Completează: „Søknaden ___ fortløpende.”', answer: 'behandles', explanation: 'Forma în „-s” exprimă pasivul formal.' },
      { type: 'order', prompt: 'Construiește „Echipa a realizat proiectul conform planului.”', words: ['som', 'Teamet', 'prosjektet', 'gjennomførte', 'planlagt'], answer: ['Teamet', 'gjennomførte', 'prosjektet', 'som', 'planlagt'], explanation: 'Expresia „som planlagt” înseamnă „conform planului”.' },
    ],
  },
  {
    id: 3, title: 'Societate și media', duration: 35,
    objectives: ['să evaluezi credibilitatea unei surse', 'să discuți influența mass-media', 'să formulezi concluzii prudente'],
    vocabulary: [
      ['Kildekritikk', 'Evaluarea critică a surselor', 'God kildekritikk er nødvendig i møte med sosiale medier.', 'Evaluarea critică a surselor este necesară în contact cu rețelele sociale.'],
      ['Pålitelig', 'De încredere', 'Vi må undersøke om kilden er pålitelig.', 'Trebuie să verificăm dacă sursa este de încredere.'],
      ['Å påvirke', 'A influența', 'Overskrifter kan påvirke hvordan vi tolker en sak.', 'Titlurile pot influența felul în care interpretăm un subiect.'],
      ['Ytringsfrihet', 'Libertate de exprimare', 'Ytringsfrihet innebærer både rettigheter og ansvar.', 'Libertatea de exprimare implică atât drepturi, cât și responsabilități.'],
      ['En fremstilling', 'O prezentare / reprezentare', 'Artikkelen gir en ensidig fremstilling av konflikten.', 'Articolul oferă o prezentare unilaterală a conflictului.'],
      ['Vesentlig', 'Substanțial / important', 'Det er en vesentlig forskjell mellom fakta og kommentar.', 'Există o diferență importantă între fapte și comentarii.'],
    ],
    dialogue: [
      ['Nora', 'Denne saken deles overalt, men jeg finner ingen tydelig kilde.', 'Această știre este distribuită peste tot, dar nu găsesc o sursă clară.'],
      ['Emil', 'Da bør vi være forsiktige med å trekke konklusjoner.', 'Atunci ar trebui să fim prudenți în formularea concluziilor.'],
      ['Nora', 'Bildet virker også å være tatt ut av sammenheng.', 'Și imaginea pare să fie scoasă din context.'],
      ['Emil', 'La oss se om redaksjonelle medier har bekreftet opplysningene.', 'Să verificăm dacă publicațiile editoriale au confirmat informațiile.'],
    ],
    grammar: { title: 'Verbe de raportare și prudență', rule: 'În discursul formal, „hevde”, „tyde på”, „ifølge” și „kan se ut til” separă faptele de interpretări.', examples: ['Studien tyder på en endring. — Studiul indică o schimbare.', 'Ifølge rapporten har bruken økt. — Potrivit raportului, utilizarea a crescut.'], wrong: 'Studien beviser kanskje helt sikkert en endring.' },
    exercises: [
      { type: 'choice', prompt: 'Ce formulare exprimă cel mai bine prudența?', options: ['Det er helt sikkert.','Studien tyder på at...','Alle vet at...'], answer: 1, explanation: '„Tyder på” prezintă o interpretare fără a o declara certitudine.' },
      { type: 'fill', prompt: 'Completează: „___ rapporten har bruken økt.”', answer: 'Ifølge', explanation: '„Ifølge” indică sursa informației.' },
      { type: 'order', prompt: 'Construiește „Trebuie să verificăm dacă sursa este de încredere.”', words: ['pålitelig', 'om', 'Vi', 'undersøke', 'kilden', 'må', 'er'], answer: ['Vi', 'må', 'undersøke', 'om', 'kilden', 'er', 'pålitelig'], explanation: 'În subordonata cu „om”, subiectul precedă verbul.' },
    ],
  },
  {
    id: 4, title: 'Climă și sustenabilitate', duration: 36,
    objectives: ['să discuți soluții de mediu', 'să descrii cauze și consecințe', 'să folosești vocabular formal despre schimbare'],
    vocabulary: [
      ['Bærekraftig', 'Sustenabil', 'En bærekraftig løsning må fungere også på lang sikt.', 'O soluție sustenabilă trebuie să funcționeze și pe termen lung.'],
      ['Utslipp', 'Emisii', 'Byen ønsker å redusere utslipp fra transport.', 'Orașul dorește să reducă emisiile din transport.'],
      ['En omstilling', 'O tranziție / restructurare', 'Grønn omstilling krever langsiktige investeringer.', 'Tranziția verde necesită investiții pe termen lung.'],
      ['Et tiltak', 'O măsură', 'Tiltaket skal gjøre det enklere å velge kollektivt.', 'Măsura va facilita alegerea transportului public.'],
      ['Fornybar', 'Regenerabil', 'Norge produserer mye fornybar energi.', 'Norvegia produce multă energie regenerabilă.'],
      ['Et forbruk', 'Un consum', 'Vi må redusere forbruket uten å øke forskjellene.', 'Trebuie să reducem consumul fără să sporim inegalitățile.'],
    ],
    dialogue: [
      ['Rådgiver', 'Kommunen vurderer å gjøre sentrum bilfritt.', 'Municipalitatea analizează transformarea centrului într-o zonă fără mașini.'],
      ['Innbygger', 'Det kan redusere utslipp, men hva med dem som bor langt unna?', 'Poate reduce emisiile, dar ce se întâmplă cu cei care locuiesc departe?'],
      ['Rådgiver', 'Tiltaket må kombineres med et bedre kollektivtilbud.', 'Măsura trebuie combinată cu o ofertă mai bună de transport public.'],
      ['Innbygger', 'Da blir omstillingen både grønnere og mer rettferdig.', 'Atunci tranziția devine atât mai verde, cât și mai echitabilă.'],
    ],
    grammar: { title: 'Cauză, efect și concesie', rule: 'Folosește „fordi” pentru cauză, „derfor” pentru efect și „selv om” pentru contrast concesiv.', examples: ['Vi endrer vaner fordi utslippene må ned. — Ne schimbăm obiceiurile pentru că emisiile trebuie reduse.', 'Selv om tiltaket er dyrt, kan det lønne seg. — Chiar dacă măsura este scumpă, poate fi rentabilă.'], wrong: 'Selv om tiltaket er dyrt, men det er nødvendig.' },
    exercises: [
      { type: 'choice', prompt: 'Ce conector introduce o concesie?', options: ['Derfor','Fordi','Selv om'], answer: 2, explanation: '„Selv om” înseamnă „chiar dacă”.' },
      { type: 'fill', prompt: 'Completează: „Utslippene må ned. ___ endrer vi vaner.”', answer: 'Derfor', explanation: '„Derfor” introduce consecința.' },
      { type: 'order', prompt: 'Construiește „Tranziția verde necesită investiții pe termen lung.”', words: ['investeringer', 'omstilling', 'langsiktige', 'krever', 'Grønn'], answer: ['Grønn', 'omstilling', 'krever', 'langsiktige', 'investeringer'], explanation: 'Adjectivul nehotărât precedă substantivul.' },
    ],
  },
  {
    id: 5, title: 'Exprimare academică și formală', duration: 38,
    objectives: ['să structurezi un răspuns formal', 'să analizezi perspective diferite', 'să formulezi o concluzie bine susținută'],
    vocabulary: [
      ['Å redegjøre for', 'A prezenta / explica', 'Innledningen redegjør for undersøkelsens formål.', 'Introducerea prezintă scopul studiului.', 'redegjør for'],
      ['Å drøfte', 'A analiza argumentativ', 'Oppgaven ber studentene drøfte to ulike perspektiver.', 'Tema le cere studenților să analizeze două perspective diferite.'],
      ['Hensiktsmessig', 'Potrivit / oportun', 'Det er hensiktsmessig å skille mellom årsak og virkning.', 'Este potrivit să distingem între cauză și efect.'],
      ['En forutsetning', 'O condiție prealabilă', 'Tillit er en forutsetning for åpen dialog.', 'Încrederea este o condiție prealabilă pentru dialog deschis.'],
      ['En sammenheng', 'O legătură / un context', 'Tallene må forstås i en større sammenheng.', 'Cifrele trebuie înțelese într-un context mai larg.'],
      ['En konklusjon', 'O concluzie', 'Konklusjonen må bygge på argumentene i teksten.', 'Concluzia trebuie să se bazeze pe argumentele din text.'],
    ],
    dialogue: [
      ['Veileder', 'Problemstillingen er interessant, men fortsatt litt for bred.', 'Problematica este interesantă, dar încă puțin prea largă.'],
      ['Student', 'Bør jeg avgrense analysen til arbeidslivet?', 'Ar trebui să limitez analiza la viața profesională?'],
      ['Veileder', 'Ja, og gjør tydelig rede for hvilke kilder du bygger på.', 'Da, și explică limpede pe ce surse te bazezi.'],
      ['Student', 'Da kan jeg drøfte funnene mer grundig.', 'Atunci pot analiza constatările mai aprofundat.'],
    ],
    grammar: { title: 'Stil nominal și formulări impersonale', rule: 'Textele formale folosesc frecvent substantive abstracte și construcții impersonale pentru un ton neutru.', examples: ['Det kan hevdes at tiltaket har effekt. — Se poate susține că măsura are efect.', 'En vurdering av resultatene er nødvendig. — Este necesară o evaluare a rezultatelor.'], wrong: 'Jeg synes liksom at resultatet er ganske bra.' },
    exercises: [
      { type: 'choice', prompt: 'Care formulare este cea mai potrivită într-un text formal?', options: ['Jeg føler at det er sånn.','Det kan hevdes at...','Alle skjønner jo at...'], answer: 1, explanation: 'Construcția impersonală păstrează un ton analitic.' },
      { type: 'fill', prompt: 'Completează: „Tallene må forstås i en større ___.”', answer: 'sammenheng', explanation: 'Expresia „i en større sammenheng” înseamnă „într-un context mai larg”.' },
      { type: 'order', prompt: 'Construiește „Concluzia trebuie să se bazeze pe argumente.”', words: ['argumentene', 'bygge', 'må', 'på', 'Konklusjonen'], answer: ['Konklusjonen', 'må', 'bygge', 'på', 'argumentene'], explanation: 'Verbul modal este urmat de infinitiv fără „å”.' },
    ],
  },
];
